### ISSUE TITLE
Offer a ready to use IAM Policy Terraform file

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#103]
**Description**
driftctl documentation explains the IAM minimal required permissions [here](https://github.com/cloudskiff/driftctl/blob/main/doc/cmd/scan/supported_resources/aws.md#least-privileged-policy)

Why not offer a simple ready to use terraform file, as @bertux suggested!

**Example**

Same content, in an IAM policy resource!

**Comment by bertux** [comment]
To suggest more, having also in the terrafom file the IAM role using this policy would be AWeSome ;-)

**Comment by bertux** [comment]
@wbeuil as discussed with @sjourdan I have already configured all the needed policies for driftctl to work with my tfstate in S3 bucket so I will use terraform import to submit the TF files in a merge request for this issue.

**Comment by bertux** [comment]
I've tried to import with the version of Terraform I used for daily work but it didn't generate the configuration and just imported it in the state as confirmer by the help precising:
```
The current implementation of Terraform import can only import resources
  into the state. It does not generate configuration. A future version of
  Terraform will also generate configuration.
```
So I will complete the TF by myself. Would you prefer to have a JSON file separated or included in the TF ?

**Comment by wbeuil** [comment]
Which JSON file do you talk about ? 

Could you just include the terraform file ? We had in mind something really simple with aws_iam_policy_document, aws_iam_role and aws_iam_role_policy resources. Feel free to reach out to me if you need further help.

**Comment by sjourdan** [comment]
Thanks, @bertux! 
IMHO for now, the IAM Policy JSON content can simply be included directly in the terraform resource, so it can be used even more easily by the users!

**Comment by bertux** [comment]
ok that confirms well what I will do this week. I just wanted to avoid quiproquo in the way of doing it.

**Comment by bertux** [comment]
I'm back, I'm trying to finish that today.

**Comment by sundowndev** [comment]
Fixed by https://github.com/cloudskiff/driftctl-docs/pull/28

**Comment by sjourdan** [comment]
LGTM! Maybe later we should write a quick blog post on how to use an IAM role, from an IAM user etc. 

```
# The role can scan 
❯  AWS_PROFILE=driftctl-role LOG_LEVEL=error driftctl-0.8.0 scan
Scanned states (1) 
Scanned resources (29)        
[...]

# but the same role can't create an s3 bucket, as expected
❯  AWS_PROFILE=driftctl-role aws s3 mb s3://lalala
make_bucket failed: s3://lalala An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied
```
