### ISSUE TITLE
driftctl needs to write your state ?

### ISSUE THREAD

**Issue by bertux** [cloudskiff/driftctl#105]
**Description**
At https://github.com/cloudskiff/driftctl/blob/main/doc/cmd/scan/iac_source.md it's written `driftctl needs to read your state` but in the IAM policy precising it there is `s3:PutObject` which can write the state so could you correct what is really needed ?
I would be surprised if driftctl really needs to modify the state so I will try without write access.

**Comment by eliecharra** [comment]
It looks like an issue in the documentation since driftctl **never mutate nothing**.

Could you try without `s3:PutObject` directive ?

**Comment by bertux** [comment]
I've tried and it worked well, so I confirm it's documentation bug easy to fix. May I propose the fix as a good way to start contributing ?

**Comment by eliecharra** [comment]
> I've tried and it worked well, so I confirm it's documentation bug easy to fix. So I am preparing the PR to fix it as a good way to start contributing.

Awesome, can't wait for it. Thanks a lot 👍🏻
