### ISSUE TITLE
Non deep-mode resources shouldn't generate noise in deep-mode

### ISSUE THREAD

**Issue by sundowndev** [cloudskiff/driftctl#1068]
**Description**

Previously, we introduced deep mode which allowed us to split the enumeration and fetching of resource details in two separate processes. This feature allows us to add support for resources only for enumeration, not deep-mode. Now that we decided to stop implementing deep-mode for new resources, future scans will attempt to read details of resources that don't have a details fetcher. The actual behavior is that those resource will appear as managed but all the attributes will appear as drifted, which brings a lot of noise in the output.

**This is a blocking issue for the next release**.

**Example**

![image](https://user-images.githubusercontent.com/16480203/133630892-a985526f-00db-4b19-b2ab-d68a659570b8.png)

**How to reproduce**

- Create a `azurerm_storage_account` resource (or any resource that doesn't support deep-mode) with Terraform
- Run a driftctl scan with `--deep` flag

Observe the whole resource's attributes being displayed as drifts.

**Possible Solution**

It's obvious we need to ignore those resources at attributes comparison when they don't have a details fetcher available. However it can be confusing to the user to not detect drifts on those resources since it can be interpreted as false negatives. May be we should display a warning message about that ?

**Comment by eliecharra** [comment]
> It's obvious we need to ignore those resources when they don't have a details fetcher available. However it can be confusing to the user to not detect drifts on those resources since it can be interpreted as false negatives. May be we should display a warning message about that ?

@sundowndev We do not want to fully ignore theses resources. Wwe only want to avoid to compare their attributes. On IaC side we always decode a deep resource, so we end by comparing a deep IaC resource with a non-deep remote one.

Maybe we can introduce a flag in resources not compatible with deep mode, and then in the analyzer we can check this flag and skip resources that are not compatible with deep mode ? WDYT @cloudskiff/engineering

**Comment by eliecharra** [comment]
I have something like that in mind

```diff
diff --git a/pkg/analyser/analyzer.go b/pkg/analyser/analyzer.go
index cb99fc70..1b3a4655 100644
--- a/pkg/analyser/analyzer.go
+++ b/pkg/analyser/analyzer.go
@@ -81,7 +81,7 @@ func (a Analyzer) Analyze(remoteResources, resourcesFromState []*resource.Resour
                analysis.AddManaged(stateRes)
 
                // Stop there if we are not in deep mode, we do not want to compute diffs
-               if !a.options.Deep {
+               if !a.options.Deep || !stateRes.HasFlag(flags.DEEP) {
                        continue
                }
```

We can use flags for other concern in the future.

**Comment by moadibfr** [comment]
> I have something like that in mind

that sounds nice

> I'm good with this approach. How would you add it though? At the creation inside CreateAbstractResource?

I think flags should be in metadatas ?

**Comment by eliecharra** [comment]
> I'm good with this approach. How would you add it though? At the creation inside `CreateAbstractResource`?

Good question, I was thinking that it could be a good idea to put this flag at resource creation in `CreateAbstractResource`, but what if for some reason (mistake or so) we end with manually create resources in the list ? It is a potential source of bugs.

Maybe it will be better to set the flag in the `scanner` when we check if the resource have a detail fetcher ?

```diff
diff --git a/pkg/remote/scanner.go b/pkg/remote/scanner.go
index c1a227d9..38b32424 100644
--- a/pkg/remote/scanner.go
+++ b/pkg/remote/scanner.go
@@ -107,6 +107,7 @@ func (s *Scanner) scan() ([]*resource.Resource, error) {
                        }
 
                        resourceWithDetails, err := fetcher.ReadDetails(res)
+                       resourceWithDetails.AddFlag(flags.DEEP)
                        if err != nil {
                                if err := HandleResourceDetailsFetchingError(err, s.alerter); err != nil {
                                        return nil, err
```

But we still have the the question for middlewares ... How to handle an expanded resource ? Should we set the flag in middleware. It's gonna be messy ... 

Maybe we can introduce a new method in `ResourceFactory` : `CreateFromParent(parent *resource.Resource, ty, id string, data map[string]interface{})` that will copy parent flags to child resource ? It may be used in the future to setup source for expanded resource too.

I do not have every case in mind unfortunatly, and this will maybe remain open to bugs ...

We can also explore other ways to achieve that, for example if we inject `RemoteLibrary` in the analyzer. I wanted to avoid that since we should not use code from remote pkg under the analyzer for me, it break separation of concern.

Maybe introduce a resource metadata store that will replace our actual `resource/resource_types.go` list and where we can define if resource should be deep mode compatible, and thus we can inject on IaC, remote and analyzer packages.

Maybe the third solution sound better ...

Waiting for your feedbacks

**Comment by moadibfr** [comment]
> Maybe introduce a resource metadata store that will replace our actual `resource/resource_types.go` list and where we can define if resource should be deep mode compatible, and thus we can inject on IaC, remote and analyzer packages.

could we just put this in the schema ? Or store it alongside the schema ?

**Comment by eliecharra** [comment]
> I think flags should be in metadatas ?

Yeah you get the same point than me when I say

> Maybe introduce a resource metadata store that will replace our actual resource/resource_types.go list and where we can define if resource should be deep mode compatible, and thus we can inject on IaC, remote and analyzer packages.

> could we just put this in the schema ? Or store it alongside the schema ?

I don't know if this should remain in our existing schema 🤔 Since it is not related to the resource logic itself (it's a driftctl logic metadata) maybe we should not put it within ...

**Comment by moadibfr** [comment]
> I don't know if this should remain in our existing schema thinking Since it is not related to the resource logic itself (it's a driftctl logic metadata) maybe we should not put it within ...

Was thinking that our schema store info about the resource and how to use it so it would'nt bother me to have flag about how to compare it ?

**Comment by eliecharra** [comment]
> Was thinking that our schema store info about the resource and how to use it so it wouldn't bother me to have flag about how to compare it ?

Do we agree on this kind of approach:

```diff
diff --git a/pkg/analyser/analyzer.go b/pkg/analyser/analyzer.go
index cb99fc70..f65d9faa 100644
--- a/pkg/analyser/analyzer.go
+++ b/pkg/analyser/analyzer.go
@@ -81,7 +81,7 @@ func (a Analyzer) Analyze(remoteResources, resourcesFromState []*resource.Resour
 		analysis.AddManaged(stateRes)
 
 		// Stop there if we are not in deep mode, we do not want to compute diffs
-		if !a.options.Deep {
+		if !a.options.Deep || !stateRes.Sch.Flags.HasFlag(resource.FLAG_DEEP_MODE) {
 			continue
 		}
 
diff --git a/pkg/resource/aws/aws_cloudformation_stack.go b/pkg/resource/aws/aws_cloudformation_stack.go
index de9baea2..d9a783d5 100644
--- a/pkg/resource/aws/aws_cloudformation_stack.go
+++ b/pkg/resource/aws/aws_cloudformation_stack.go
@@ -10,6 +10,7 @@ import (
 const AwsCloudformationStackResourceType = "aws_cloudformation_stack"
 
 func initAwsCloudformationStackMetaData(resourceSchemaRepository resource.SchemaRepositoryInterface) {
+	resourceSchemaRepository.SetFlags(AwsCloudformationStackResourceType, resource.FLAG_DEEP_MODE)
 	resourceSchemaRepository.SetResolveReadAttributesFunc(AwsCloudformationStackResourceType, func(res *resource.Resource) map[string]string {
 		attrs := make(map[string]interface{})
 		if v := res.Attributes().GetMap("parameters"); v != nil {
diff --git a/pkg/resource/schemas.go b/pkg/resource/schemas.go
index 7aaf62d7..a71a9d71 100644
--- a/pkg/resource/schemas.go
+++ b/pkg/resource/schemas.go
@@ -14,8 +14,18 @@ type AttributeSchema struct {
 	JsonString   bool
 }
 
+type Flags uint32
+
+const (
+	FLAG_DEEP_MODE Flags = 1 << iota
+)
+
+func (f Flags) HasFlag(flag Flags) bool { return f&flag != 0 }
+func (f *Flags) AddFlag(flag Flags)     { *f |= flag }
+
 type Schema struct {
 	ProviderVersion             *version.Version
+	Flags                       *Flags
 	SchemaVersion               int64
 	Attributes                  map[string]AttributeSchema
 	NormalizeFunc               func(res *Resource)
@@ -41,6 +51,7 @@ func (s *Schema) IsJsonStringField(path []string) bool {
 
 type SchemaRepositoryInterface interface {
 	GetSchema(resourceType string) (*Schema, bool)
+	SetFlags(typ string, flags ...Flags)
 	UpdateSchema(typ string, schemasMutators map[string]func(attributeSchema *AttributeSchema))
 	SetNormalizeFunc(typ string, normalizeFunc func(res *Resource))
 	SetHumanReadableAttributesFunc(typ string, humanReadableAttributesFunc func(res *Resource) map[string]string)
@@ -106,6 +117,17 @@ func (r *SchemaRepository) Init(providerName, providerVersion string, schema map
 	return nil
 }
 
+func (r SchemaRepository) SetFlags(typ string, flags ...Flags) {
+	metadata, exist := r.GetSchema(typ)
+	if !exist {
+		logrus.WithFields(logrus.Fields{"type": typ}).Warning("Unable to set metadata, no schema found")
+		return
+	}
+	for _, flag := range flags {
+		metadata.Flags.AddFlag(flag)
+	}
+}
+
 func (r *SchemaRepository) UpdateSchema(typ string, schemasMutators map[string]func(attributeSchema *AttributeSchema)) {
 	for s, f := range schemasMutators {
 		metadata, exist := r.GetSchema(typ)

```

**Comment by moadibfr** [comment]
> Do we agree on this kind of approach:

yep that's what I had in mind !

**Comment by wbeuil** [comment]
Good with that 🤘

**Comment by eliecharra** [comment]
> @eliecharra How would you handle flags for virtual resources with this approach ? Isn't it possible to add the flag automatically when adding a details fetcher for example ?

This is not an issue since the flag is setup on resource schema not on the resource itself, so it will work for all resources of the same type.

**Comment by sjourdan** [comment]
LGTM, couldn't find any weird behavior with non-deep mode supported resources.

```
❯  LOG_LEVEL=error driftctl-0.16-pre scan -t azure+tf --deep
Found resources not covered by IaC:
  azurerm_storage_account:
    - /subscriptions/7bfb2c5c-7308-46ed-8ae4-fffa356eb406/resourceGroups/driftctl-sj-tests/providers/Microsoft.Storage/storageAccounts/driftctlsjtestssa
  azurerm_virtual_network:
    - /subscriptions/7bfb2c5c-7308-46ed-8ae4-fffa356eb406/resourceGroups/driftctl-sj-tests/providers/Microsoft.Network/virtualNetworks/manual-network
Found 3 resource(s)
 - 33% coverage
 - 1 resource(s) managed by terraform
     - 0/1 resource(s) out of sync with Terraform state
 - 2 resource(s) not managed by Terraform
 - 0 resource(s) found in a Terraform state but missing on the cloud provider
Scan duration: 2s
```
