### ISSUE TITLE
aws_instance + aws_eip require 2 tf applies to stop falsely drift

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#11]
**Description**
When adding an aws_eip to an aws_instance, 2 applies are needed to update the state and driftctl to stop seeing a drift (while there's none)

It is a Terraform issue and not driftctl, but still we report a drift while there's none

```
Found 2 differences in managed resource: i-0fe2f966f41521b44 (aws_instance):
         ~ PublicDns: "ec2-35-180-34-37.eu-west-3.compute.amazonaws.com" => "ec2-15-237-90-99.eu-west-3.compute.amazonaws.com"
         ~ PublicIp: "35.180.34.37" => "15.237.90.99"
```

**Environment**
 - OS: linux
 - driftctl version: v0.1.0

**How to reproduce**

[to_reproduce.tar.gz](https://github.com/cloudskiff/driftctl/files/5688191/to_reproduce.5.tar.gz)

- apply the ec2 tf
- run driftctl scan
- see error
- apply again tf
- run driftctl scan
- See error gone

**Possible Solution**
We could ignore these fields from diff when we got an `aws_eip_association` resource attached to the instance as it is a duplicate drift information. 

cases to test:

-
  - create an instance without eip
  - driftctl scan
  - **Actual**: no drift **Expected** : no drift
- 
  - create an instance with eip
  - driftctl scan
  - **Actual**: drift **Expected**: no drift
- 
  - create an instance with eip
  - driftctl scan
  - **Actual**: drift **Expected**: no drift
  - manual assign a new eip
  - driftctl scan
  - **Actual**: drift **Expected**: drift ⚠️ but this is an invalid drift, expected a drift between the first eip and the second, got a drift between instance dynamic assigned ip during creation and second eip
-
  - create an instance without eip
  - driftctl scan
  - **Actual**: no drift **Expected** : no drift
  - manual stop and restart instance (trigger ip change without eip association)
  - **Actual**: drift **Expected**: drift
-
  - create an instance with eip
  - driftctl scan
  - **Actual**: drift **Expected** : no drift
  - manual stop and restart instance (trigger ip change without eip association)
  - **Actual**: drift **Expected**: no drift

**Additional context**
```
$    AWS_REGION="eu-west-3" AWS_PROFILE="cloudskiff-demo" driftctl scan 
ERRO[2020-10-27T14:38:33+01:00] unsupported attribute "block_device_mappings" 
Found 5 unmanaged resources, 0 deleted resources. 2 resources have drifted.
[...]
Found 2 differences in managed resource: i-0fe2f966f41521b44 (aws_instance):
         ~ PublicDns: "ec2-35-180-34-37.eu-west-3.compute.amazonaws.com" => "ec2-15-237-90-99.eu-west-3.compute.amazonaws.com"
         ~ PublicIp: "35.180.34.37" => "15.237.90.99"
[...]
Total coverage is 28%

$    AWS_REGION="eu-west-3" AWS_PROFILE="cloudskiff-demo" terraform apply 
random_string.prefix: Refreshing state... [id=do4luh]
data.aws_ami.ubuntu: Refreshing state...
aws_instance.test_instance_1: Refreshing state... [id=i-0fe2f966f41521b44]
aws_eip.eip_test_instance_1: Refreshing state... [id=eipalloc-059d78c79c2d54262]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

$    AWS_REGION="eu-west-3" AWS_PROFILE="cloudskiff-demo" driftctl scan 
ERRO[2020-10-27T14:39:40+01:00] unsupported attribute "block_device_mappings" 
Found 5 unmanaged resources, 0 deleted resources. 1 resources have drifted.
[...]
Total coverage is 28%
```

**Comment by sjourdan** [comment]
LGTM! The false positive drift detected on 0.1.0 is not there anymore on 0.1.1
