### ISSUE TITLE
Replace manual terraform execution and use hashicorp provided library

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#119]
Terraform is executed in acceptance tests

```go
func (c *AccTestCase) terraformInit() error {
	_, err := os.Stat(path.Join(c.Path, ".terraform"))
	if os.IsNotExist(err) {
		logrus.Debug("Running terraform init ...")
		cmd := exec.Command("terraform", "init", "-input=false")
		cmd.Dir = c.Path
		out, err := cmd.CombinedOutput()
		if err != nil {
			return errors.Wrap(err, string(out))
		}
		logrus.Debug("Terraform init done")
	}

	return nil
}

func (c *AccTestCase) terraformApply() error {
	logrus.Debug("Running terraform apply ...")
	cmd := exec.Command("terraform", "apply", "-auto-approve")
	cmd.Dir = c.Path
	out, err := cmd.CombinedOutput()
	if err != nil {
		return errors.Wrap(err, string(out))
	}
	logrus.Debug("Terraform apply done")

	return nil
}
```

We could simplify this code by using this library

- https://github.com/hashicorp/terraform-exec

**Comment by sshota0809** [comment]
Hi @eliecharra
I read sources of the terraform-exec module and I would like to try this issue.
Is that ok with you?

**Comment by eliecharra** [comment]
Sure go on, we would be very happy to merge your work 😃 

Just adding details below.

- Be careful with terraform installation
  - we don't want to trigger a terraform installation on each test, it will add a lot of overhead. Actually terraform is a requirement and should be installed on system. It would be nice to be able to use and auto install a specific version to be independent from environment. But it should be done once and reused if you run acceptance test multiples times. So maybe we need to think a little about this, maybe we could install binaries in a tmp folder (should be cross platform). I don't know how hashicorp's library is handling that.
  - in case of error during init or apply we want to view the terraform output in the test for debugging purposes
  - We should always install a predictible terraform version : 0.14.5 (not the latest one)

**Comment by sshota0809** [comment]
@eliecharra 
Thank you for reply

> we don't want to trigger a terraform installation on each test, it will add a lot of overhead. Actually terraform is a requirement and should be installed on system. It would be nice to be able to use and auto install a specific version to be independent from environment. But it should be done once and reused if you run acceptance test multiples times. So maybe we need to think a little about this, maybe we could install binaries in a tmp folder (should be cross platform). I don't know how hashicorp's library is handling that.

I'm ok with this, I agree with your opinion. By the way, as log as I read sources of the terraform-exec It seems that we can install specific or latest version of terraform temporarily.

> in case of error during init or apply we want to view the terraform output in the test for debugging purposes

Please let me know about this, this means only stderr or both stdout and stderr?

> We should always install a predictible terraform version : 0.14.5 (not the latest one)

On present implementation, It seems that ACC test don't check terraform version in developer's local. Would you want ACC test to check if terraform version is supported or not, if so I'm going to implement it!

Thanks for your looking my reply.

**Comment by eliecharra** [comment]
> Please let me know about this, this means only stderr or both stdout and stderr?

I think actually it only return stderr

> On present implementation, It seems that ACC test don't check terraform version in developer's local. Would you want ACC test to check if terraform version is supported or not, if so I'm going to implement it!

Actually it's a weakness you are right. It may loose sense to check version if we use the version installed by terraform-exec. I think ACC test should be independent from the local environment.

Let me know if you have other questions !

**Comment by sshota0809** [comment]
@eliecharra 
Thanks a lot!

I think we should deal with this issue like following two issue separately.

1. Replace manual terraform execution using terraform-exec
2. Install terraform for ACC test through terraform-exec and be able to execute ACC test being independent from the developer's local.

How about resolve No.1 as this issue? And after that, We will create new issue about No.2. First of all, I would like to try to focus on No.1.

What do you think about this? Please let me know your opinion.

**Comment by eliecharra** [comment]
Separate and conquer 👍🏻 

I totally agree with you if we could split we should make two separate issues.

Anyway, I don't think it will be useful to add version check in No.1 as we will not use locally installed terraform anymore in the future.

**Comment by sshota0809** [comment]
@eliecharra 
Then I'm going to implement with No.1. I will push PR as soon as I will be done with it!

Please give me several days :bow:

**Comment by sshota0809** [comment]
Hi, @eliecharra 

Thank you for merging my PR. 

> 1. Replace manual terraform execution using terraform-exec. (At this point, ACC test still depend on developer's local terraform version.)
> 2. Install terraform for ACC test through terraform-exec and be able to execute ACC test being independent from the developer's local.

We have completed No.1, so can you close this issue? After that I will create new issue related to No.2.

**Comment by eliecharra** [comment]
Sure let's close this. Can I let you and open the new one ?
