### ISSUE TITLE
Ability to ignore a single field on a given resource

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#13]
**Description**
We want to be able to ignore from drift a single field of a resource.

**Example**
I create an `aws_lambda_function`

```
resource "aws_lambda_function" "foobar" {
  function_name = "foobar"
  role          = "foobar"
  filename      = "data/lambda/something.zip"
  handler       = "main"
  timeout       = 15
  runtime       = "go1.x"

  lifecycle {
    ignore_changes = [
      environment,
    ]
  }
}
```

I update my lambda environment using a CI pipeline.
**I don't want driftctl to show me environment drifts**

**Comment by bytejunkie** [comment]
i see that this will be 0.2, i thought i'd add a use case for this one on the off chance that it helps.

i would like to be able to ignore the members of a target group on a load balancer, as these will change in production from time to time. we might choose to move one server into the group to add capacity, or one server out to patch/rebuild. the fact that there is a target group is important and should be covered, but the ability to specify that the targets are less important and might vary would be useful.

**Comment by eliecharra** [comment]
Thanks a lot @bytejunkie for your feedback 👍🏻 

We we'll keep your usecase in mind when we'll add support for load balancers.
