### ISSUE TITLE
ignored aws_route53_record is not ignored

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#154]
**Description**

Adding a "aws_route53_record" line to my `.gitignore` doesn't ignore the record. 

**Environment**
 - OS: ubuntu 20.04
 - driftctl version: 0.2.3 & 3197b83-dev

**How to reproduce**

Launch driftctl against an AWS account with a route53 record and try to ignore it.

**Possible Solution**

**Additional context**

```
$ grep Z002310315S6E3IT1NYWA_cia.gov_A .driftignore
aws_route53_record.Z002310315S6E3IT1NYWA_cia.gov_A

$ driftctl scan
Scanning AWS on region: us-east-1
Found unmanaged resources:
  aws_route53_record:
    - Z002310315S6E3IT1NYWA_cia.gov_A
[...]
Found 6 resource(s)
 - 50% coverage
 - 3 covered by IaC
 - 3 not covered by IaC
 - 0 deleted on cloud provider
 - 0/3 drifted from IaC
 ```

Debug in dev build shows: 

```
DEBU[0007] Reading aws cloud resource attrs=map[] id=Z002310315S6E3IT1NYWA_cia.gov_A type=aws_route53_record
DEBU[0011] Ignoring default unmanaged record id=Z002310315S6E3IT1NYWA_cia.gov_NS type=aws_route53_record
DEBU[0011] Ignoring default unmanaged record id=Z002310315S6E3IT1NYWA_cia.gov_SOA type=aws_route53_record
DEBU[0011] Found ignore resource field rule in .driftignore id=Z002310315S6E3IT1NYWA_cia path=gov_A type=aws_route53_record
```

**Comment by sjourdan** [comment]
the issue was between the chair and the keyboard (and that was not missing documentation)
thanks @eliecharra  :)

**Comment by eliecharra** [comment]
dots in resources ID must be escaped, you should write `aws_route53_record.Z002310315S6E3IT1NYWA_cia\.gov_A` (check the backslash) in your ignore.

Documentation reference https://github.com/cloudskiff/driftctl/blob/main/doc/cmd/scan/filter.md#driftignore
