### ISSUE TITLE
Disable warning in driftignore parsing

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#157]
**Description**
I would like to add comment in my driftignore, but when running driftctl it output multiples warnings.
We could skip lines starting with a `#` and empty lines

**Example**
```ignore
# intern laptop admin credentials
# TODO : remove tf-admin user and provision a key for intern user
aws_iam_user.tf-admin
aws_iam_access_key.XXXXXXXXXXXXXXX
aws_iam_policy_attachment.tf-admin-arn:aws:iam::aws:policy/AdministratorAccess

# Terraform bucket for state storage
aws_s3_bucket.remote-states
```

![image](https://user-images.githubusercontent.com/6154987/106042793-cee3b300-60dd-11eb-8c34-72317e8a7ef9.png)

**Comment by sfenman** [comment]
Hi @eliecharra , I would like to give it a try if it's possible!

**Comment by eliecharra** [comment]
Sure go on it would be awesome to merge your contribution !
