### ISSUE TITLE
Suppliers have mutual hidden dependency

### ISSUE THREAD

**Issue by moadibfr** [cloudskiff/driftctl#165]
**Description**
We may want to handle differently how we list resource to prevent this

**Comment by eliecharra** [comment]
Each supplier must be totally independent and do not call other provider methods.

For caching purpose we may want to wrap the aws client in our own struct.

**Comment by sjourdan** [comment]
will update the issue when starting the work on the issue

**Comment by lotoussa** [comment]
Suppliers to modify

- pkg/remote/aws/
- [ ] iam_access_key_supplier.go
- [ ] iam_policy_supplier.go
- [ ] iam_role_policy_attachment_supplier.go
- [ ] iam_role_policy_supplier.go
- [ ] iam_role_supplier.go
- [ ] iam_user_policy_attachment_supplier.go
- [ ] iam_user_policy_supplier.go
- [ ] iam_user_supplier.go
- [ ] internet_gateway_supplier.go
- [ ] nat_gateway_supplier.go
- [ ] route_supplier.go
- [ ] route_table_association_supplier.go
- [ ] route_table_supplier.go
- [ ] subnet_supplier.go
- [ ] vpc_security_group_rule_supplier.go
- [ ] vpc_security_group_supplier.go
- [ ] vpc_supplier.go
