### ISSUE TITLE
Add support for http state backend

### ISSUE THREAD

**Issue by nagyv** [cloudskiff/driftctl#176]
**Description**

As I really like GitLab's Managed Terraform state offering (my team developed it), my initial idea was that it would be great to have support for it with `driftctl` in a similar fashion as an `s3` bucket can be specified.

The GitLab Managed Terraform state is actually just an http backend where GitLab CI receives the environment variables that help with setting up the backend, and the CI takes care of a properly argumented `terraform init` call. So, the feature is about providing http state backend support.

It would be even better if the necessary settings would come from the `backend` config. Thus it might be related to https://github.com/cloudskiff/driftctl/issues/88

**Example**

```
driftctl scan --from tfstate+https://gitlab.com/api/v4/projects/<YOUR-PROJECT-ID>/terraform/state/<YOUR-STATE-NAME>"
```

Is this something that could be interesting to the `driftctl` community?

**Comment by eliecharra** [comment]
Hi @nagyv thanks for your feedback and your interest in driftctl.

You can use driftctl in your workflow by using terraform to handle your remote state.

You can retrieve your state using terraform and output it to a file using `terraform state pull > my-state.tfstate`
And then you can simply do  `driftctl scan --tfstate://my-state.tfstate`

Actually we are not focusing on it on our side as every state backend could be supported through `terraform state pull`
We'll be glad to review and merge community PR to support more backend without the need of pulling state using terraform 😃

**Comment by sundowndev** [comment]
We're working on this at #335 so you can provide a plain http URL (`tfstate+https`), but we're willing to implement another backend to better support Git repositories (`tfstate+git`) because if we take your example, Gitlab returns a JSON response with a base64 encoded file. Which means Git needs its dedicated backend.

**Comment by sjourdan** [comment]
LGTM! 

I confirm that trying to use an invalid HTTPS server doesn't work: 

```shell
$ driftctl scan --from tfstate+https://<redacted>.com/tfstate/terraform.tfstate
Scanning resources:
Get "https://<redacted>.com/tfstate/terraform.tfstate": x509: certificate has expired or is not yet valid: current time 2021-03-26T17:37:43+01:00 is after 2020-08-04T00:12:43Z
```

404 handling is not super obvious, but I'll open a different issue: 

```shell
$ driftctl scan --from tfstate+https://<redacted>.net/tfstates/wrong.tfstate
Scanning resources: ⣾ (0)
2 problems:

- Unsupported state file format: The state file could not be parsed as JSON: syntax error at byte offset 1.
- Unsupported state file format: The state file does not have a "version" attribute, which is required to identify the format version.
```

and finally a proper usage over HTTPS worked well 

```shell
$ driftctl scan --from tfstate+https://<redacted>.net/tfstates/terraform.tfstate
Scanning resources: ⣾ (54)
Found unmanaged resources:
  aws_iam_policy_attachment:
    - labs-arn:aws:iam::aws:policy/AmazonSQSFullAccess
  aws_lambda_event_source_mapping:
    - Source: arn:aws:sqs:us-east-1:141177182257:queue-6qaidu.fifo Dest: arn:aws:lambda:us-east-1:141177182257:function:lk6n03-lambda-demo
Found 8 resource(s)
 - 75% coverage
 - 6 covered by IaC
 - 2 not covered by IaC
 - 0 deleted on cloud provider
 - 0/6 drifted from IaC
```
