### ISSUE TITLE
Add MacPorts documentation

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#217]
**Description**

@herbygillot is maintaining a MacPorts version. Let's document usage for mac users not using homebrew! (@wbeuil you own a macintosh, can you check? 🙏🏻 )

**Comment by herbygillot** [comment]
Much appreciated @sjourdan

**Comment by wbeuil** [comment]
Tested it this morning and it looks good ! I'll open a PR to add the installation. Thanks @herbygillot !

**Comment by wbeuil** [comment]
@all-contributors please add @herbygillot for tool
