### ISSUE TITLE
ACC test should be independent from the local environment.

### ISSUE THREAD

**Issue by sshota0809** [cloudskiff/driftctl#219]
This is related to #119.

Currently ACC test is dependent on the local envirnment. it's executed with local version of terraform. That means local version of terrafrom should be supported by driftctl. That might bother developers.

Once ACC test is launched, terraform should be installed automatically as temporary for ACC test.
 
In #119, I mentioned about this as following.

> 2. Install terraform for ACC test through terraform-exec and be able to execute ACC test being independent from the developer's local.

**Comment by eliecharra** [comment]
@sjourdan Nothing to test here for you, closing
