### ISSUE TITLE
.driftignore could allow a wildcard within a ResourceId after a prefix

### ISSUE THREAD

**Issue by psedge** [cloudskiff/driftctl#232]
**Description**

Right now there are two cases covered by `.driftignore`:

1. To ignore an explicit `res.TerraformType`.`res.TerraformId` pair
2. To ignore any ID with type `res.TerraformType` using a wildcard '*'

I have a use-case where it would be useful to be able to ignore a set of `res.TerraformId`s which match a simple prefix pattern, for resources like: `aws_iam_policy_attachment.AWSServiceRoleFor{X}`. I believe that I can probably achieve the same with Filters, which I'll try next - but it would be really nice to keep rules like this within the `.driftignore` file for ease of use.

**Example**

The following `.driftignore` should ignore resources like ` AmazonSSMRoleForInstances` and. `aws_iam_role.AWSServiceRoleForAmazonSSM`:

```.driftignore
aws_iam_role.Amazon*
aws_iam_role.AWSServiceRole*
```

**Comment by eliecharra** [comment]
> **Description**
> 
> Right now there are two cases covered by `.driftignore`:
> 
> 1. To ignore an explicit `res.TerraformType`.`res.TerraformId` pair
> 2. To ignore any ID with type `res.TerraformType` using a wildcard '*'

Juste to complete initial description 😉 

3. : To ignore a specific field of a resource `res.TerraformType.Tags` for example

Thanks for reporting this to us @psedge, this issue is pretty easy to fix, for some people interested in submitting a pull-request, you have to update how we match wildcards in `driftignore.go` `IsResourceIgnored`

```go
_, isExclusionRule := r.resExclusionList[fmt.Sprintf("%s.%s", res.TerraformType(), res.TerraformId())]
```

**Comment by sjourdan** [comment]
LGTM! 

`aws_iam_policy_attachment.*azonSQ*`  in `.driftignore`  definitely ignored the following:

```
  aws_iam_policy_attachment:
    - labs-arn:aws:iam::aws:policy/AmazonSQSFullAccess
```
