### ISSUE TITLE
Unable to decode resource from state name=instance type=aws_instance

### ISSUE THREAD

**Issue by kleidcmp** [cloudskiff/driftctl#255]
We have an S3 bucket filled with .tfstates which should cover 99% of what's in the AWS account. I'm using v0.4.0.

```
 export TFS=$(aws s3 ls s3://state-bucket --recursive | grep tfstate | gawk '{ print " --from tfstate+s3://state-bucket/"$4 }')
```

```
$ ./driftctl scan $TFS --error-reporting
Scanning AWS on region: us-east-1
ERRO[0001] Unable to decode resource from state name=instance type=aws_instance
ERRO[0001] Unable to scan resources: attribute "secondary_private_ips" is required
unable to run driftctl
Sending error report ...ERRO[0001] Unable to decode resource from state name=instance type=aws_instance
ERRO[0001] Unable to decode resource from state name=instance type=aws_instance
ERRO[0001] Unable to decode resource from state name=instance type=aws_instance
ERRO[0001] Unable to decode resource from state name=instance type=aws_instance
ERRO[0001] Unable to decode resource from state name=instance type=aws_instance
ERRO[0001] Unable to decode resource from state name=instance type=aws_instance
ERRO[0001] Unable to decode resource from state name=instance type=aws_instance
ERRO[0001] Unable to decode resource from state name=instance type=aws_instance
ERRO[0001] Unable to decode resource from state name=instance type=aws_instance
 done, thank you ❤️
$ echo $?
1
```

**Comment by eliecharra** [comment]
Hi @kleidcmp tanks for your interest in driftctl.
Which version of AWS provider are you using ?

We are only supporting AWS provider >= 3.19

You can check `doc/LIMITATIONS.md` for known limitations.

**Comment by kleidcmp** [comment]
Hey @eliecharra, do you mean which version of the AWS provider created the .tfstate files, or which version is driftctl itself using? Driftctl itself picked `/home/idcmp/.driftctl/plugins/linux_amd64/terraform-provider-aws_v3.19.0_x5`.

**Comment by eliecharra** [comment]
@kleidcmp I mean the provider that generated the state.

**Comment by kleidcmp** [comment]
Ah, okay. Yeah, that could be a while before all our TF's are that up to date. 

Thank you!

**Comment by eliecharra** [comment]
Yeah we need to think a better way to handle versioning internally as our actual approach will not scale. I'm closing this issue as this in a known limitation and btw this is documented there https://github.com/cloudskiff/driftctl/blob/main/doc/LIMITATIONS.md.
