### ISSUE TITLE
Display a progress message when scanning resources

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#257]
**Description**
Scanning resources could be a long process, we want to display something to user to show that something is running and the process is still running.

**Example**
```
Found 25 resources ...
Found 30 resources ...
[...]
```

**Comment by williamcodes** [comment]
Good lord, is this why it seems like it's just hanging indefinitely when you run a scan? I thought it was broken! I've been restarting it and tweaking the flags! Please, yes, absolutely, put some output on screen and save people all this wasted time.

**Comment by mwarkentin** [comment]
This would be great, when running driftctl against one of our smaller sandbox environments it ran and returned the output very quickly. When I tried it against one of our larger accounts, it hung for an hour until I killed it and I couldn't tell if it was working or where it was getting hung up. The larger account also had dozens of terraform states, so I was also trying to figure out if I'd passed in the flags correctly which made it harder to tell if it was working correctly.

**Comment by sjourdan** [comment]
LGTM! 

- the counter is incremented as resources are found 
- the ascii spinner is moving as it's running and discovering resources 
 
```shell 
$ driftctl scan --from tfstate+s3://driftctl-tfstates/
Scanning resources: ⢿ (48)
[...]
```

**Comment by jacalata** [comment]
I just installed the most recent windows version and I don't get any response when I run driftctl. Presumably this change is in there - are there any debug logs being created as well?

**Comment by eliecharra** [comment]
> I just installed the most recent windows version and I don't get any response when I run driftctl. Presumably this change is in there - are there any debug logs being created as well?

Yeah you can try to run driftctl with env var `LOG_LEVEL=debug`

**Comment by jacalata** [comment]
Hm, I'm not seeing any output still, although I can see about 70 processes/threads in procexp so it's probably doing something. I've tried running with and without --from.

**Comment by jacalata** [comment]
it does give this output when I kill it (here it ran for almost 20 minutes, then showed that WARN on ctrl-c)
12:34:13.10|D:\dev\webhooks\webhooks-delivery-lambda\terraform>driftctl scan --from tfstate+s3://webhooks-delivery-development.terraform-remote-state.tabint.net
[1;33mWARN[0m[1107][97m Detected interrupt during terraform provider configuration, cleanup ...[0m
12:53:33.24|D:\dev\webhooks\webhooks-delivery-lambda\terraform>

**Comment by eliecharra** [comment]
> Hm, I'm not seeing any output still

Hmm maybe it is a windows issue, we do not have a lot of users on windows so maybe they remain strange platform related bugs.

You open a bug with details () for the debug logs not showing : how do you setup the env var, what kind of terminal you are using etc ... It may help us to debug your freeze issue first

In a second time, we'll need every possible details of your setup for the "freeze" issue : how to do authenticate to AWS, what version of aws terraform provider you are using, etc ... There is a known issue with SSO authentification is some aws provider versions.

Anyway, I don't think this is related to this progress message issue
