### ISSUE TITLE
Support Named Profiles

### ISSUE THREAD

**Issue by jered-miller** [cloudskiff/driftctl#26]
**Description**

Support the use of named profiles for execution, based on AWS credential documentation.

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

**Example**

driftctl scan --profile profile_name

**Comment by eliecharra** [comment]
@jered-miller This is already supported by the underlying AWS Golang SDK used by driftctl.

You could do `AWS_PROFILE=profile_name driftctl scan`

I will update the readme to add an example of usage.

**Comment by eliecharra** [comment]
Closing this one, if you need support on this feature please join us on [Discord](https://discord.gg/eYGHUa75Q2)
