### ISSUE TITLE
Show the user which .driftignore line is invalid

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#274]
**Description**

Simple UX in warnings

Today driftctl only displays which resource is concerned by the error, like: 

`WARN[0017] unable to parse line, invalid length, got 1 expected >= 2 line=github_repository.`

It would be easier for the user if it read sth like: 

`WARN[0017] unable to parse line, invalid length, got 1 expected >= 2 line=63`
**Example**

1. add an invalid line to your .driftignore
2. run driftctl

**Comment by eliecharra** [comment]
> Today driftctl only displays which resource is concerned by the error, like:

We display the full line which can't be parsed, we can add the line number
