### ISSUE TITLE
Drift Detection for manual CloudFront Behavior Improvements

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#277]
![image](https://user-images.githubusercontent.com/419121/108399914-f03a4980-721a-11eb-908d-f589c4c0cbd5.png)

**Description**
a manual behavior in a cloudfront distribution outputs a lot that could be ignored

**Environment**
 - OS: linux
 - driftctl version: 0.5 (prerel)

**How to reproduce**

- create a distribution w/s3
- create a manual behavior

**Possible Solution**

**Additional context**

**Comment by wbeuil** [comment]
@sjourdan @eliecharra I would love to know what you would expect to have as drifted attributes here.

Since this is a new cache behaviour (e.g. a new item in the list of behaviors) I would personally expect to have something like that:

```
Found drifted resources:
  - E29PCKZ0LYCGT2 (aws_cloudfront_distribution):
    + OrderedCacheBehavior.2.PathPattern: <nil> => "/yadda"
    + OrderedCacheBehavior.2.TargetOriginId: <nil> => "S3-foo-cloudfront"
```

**Comment by eliecharra** [comment]
> @sjourdan @eliecharra I would love to know what you would expect to have as drifted attributes here.
> 
> Since this is a new cache behaviour (e.g. a new item in the list of behaviors) I would personally expect to have something like that:
> 
> ```
> Found drifted resources:
>   - E29PCKZ0LYCGT2 (aws_cloudfront_distribution):
>     + OrderedCacheBehavior.2.PathPattern: <nil> => "/yadda"
>     + OrderedCacheBehavior.2.TargetOriginId: <nil> => "S3-foo-cloudfront"
> ```

Sounds good to me, we should only ensure that `<nil> => DEFAULT_VALUES` case are handled and will not display any noise for existing array elements.

![image](https://user-images.githubusercontent.com/6154987/108991929-fc019200-7698-11eb-9568-3521d15d427a.png)

**Comment by sjourdan** [comment]
LGTM

Here's with a manually added path patterrn 
and a modified tf-managed path pattern 

```

$ LOG_LEVEL=info driftctl-0.6 scan --from tfstate+s3://driftctl-tfstates/
Terraform provider initialized (name=aws, alias=us-east-1)
INFO[0002] Start reading IaC
INFO[0003] Start scanning cloud provider
Terraform provider initialized (name=aws, alias=eu-north-1)
Terraform provider initialized (name=aws, alias=eu-west-3)
Found drifted resources:
  - E9JYZTKMH4Y6F (aws_cloudfront_distribution):
    + OrderedCacheBehavior.2.Compress: <nil> => false
    + OrderedCacheBehavior.2.TargetOriginId: <nil> => "myS3Origin"
    + OrderedCacheBehavior.2.SmoothStreaming: <nil> => false
    + OrderedCacheBehavior.2.PathPattern: <nil> => "/yadda"
    + OrderedCacheBehavior.2.MinTtl: <nil> => 0
    + OrderedCacheBehavior.2.MaxTtl: <nil> => 0
    + OrderedCacheBehavior.2.DefaultTtl: <nil> => 0
    + OrderedCacheBehavior.2.AllowedMethods: <nil> => ["GET","HEAD"]
    + OrderedCacheBehavior.2.CachedMethods: <nil> => ["GET","HEAD"]
    + OrderedCacheBehavior.2.ViewerProtocolPolicy: <nil> => "allow-all"
    - DefaultCacheBehavior.0.AllowedMethods.0: "DELETE" => <nil>
    - DefaultCacheBehavior.0.AllowedMethods.6: "PUT" => <nil>
    - DefaultCacheBehavior.0.AllowedMethods.5: "POST" => <nil>
    - DefaultCacheBehavior.0.AllowedMethods.4: "PATCH" => <nil>
    - DefaultCacheBehavior.0.AllowedMethods.3: "OPTIONS" => <nil>
    ~ DefaultCacheBehavior.0.MinTtl: 0 => 666
    ~ DefaultCacheBehavior.0.ViewerProtocolPolicy: "allow-all" => "redirect-to-https"
Found 3 resource(s)
 - 100% coverage
 - 3 covered by IaC
 - 0 not covered by IaC
 - 0 deleted on cloud provider
 - 1/3 drifted from IaC


```
