### ISSUE TITLE
Publish a ROADMAP.md file

### ISSUE THREAD

**Issue by LogicNinja** [cloudskiff/driftctl#30]
I know this is early days for this tool but, it looks like it's purely AWS only for now. Are the plans to expand support for Azure and GCP platforms?

**Comment by sjourdan** [comment]
hey @LogicNinja, thanks!
Azure and GCP are definitely in the plans! We'll start to support a 2nd IaaS around March '21.
We currently have more requests for Azure support than for GCP, which one would _you_ vote for?

**Comment by eliecharra** [comment]
@sjourdan Maybe we could share with the community a ROADMAP.md and add a link tot he roadmap to the main README ?

For example : https://github.com/hashicorp/terraform-provider-aws/blob/master/ROADMAP.md

**Comment by wbeuil** [comment]
I agree with @eliecharra, this could be a good idea

**Comment by sjourdan** [comment]
most definitely!

**Comment by LogicNinja** [comment]
Awesome, that's great to hear.
Agree with @eliecharra, would be good to share this.

Azure is the one myself and my team would get the most benefit from. We have stuff across all three vendors but Azure sees the most deployments with terrraform

**Comment by jayanth-iyer** [comment]
I would definitely like to take up this documentation - ROADMP.MD - never contributed to OSS - this can be my start, i know I will have to speak core developers first to know the roadmap

Let me know unless someone else has taken this up

**Comment by eliecharra** [comment]
@jayanth-iyer Thanks for your interest in driftctl !

Thank you for your proposal, but we need to discuss about it internally before exposing something publicly.
We have a meetup dedicated to this subject on Wednesday, so we will probably publish a roadmap soon 😃 

If you wish to make a contribution, you could check at issues tagged with **good first issue** : https://github.com/cloudskiff/driftctl/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by jayanth-iyer** [comment]
Thanks @eliecharra

**Comment by czedyousfi** [comment]
Hello ! How can we vote for Azure or GCP integration ? I would be very interested in GCP integration

**Comment by eliecharra** [comment]
@czedyousfi You can upvote here https://github.com/cloudskiff/driftctl/discussions/101
