### ISSUE TITLE
Update documentation examples to encourage the use of pointers on method receivers

### ISSUE THREAD

**Issue by lotoussa** [cloudskiff/driftctl#302]
**Description**
Wouldn't it be a good idea to use pointers to avoid multiple copies of resources in memory, so change this part of the doc (and code) in order to add pointers to receiver ?

Normalize part:
https://github.com/cloudskiff/driftctl/blob/main/docs/new-resource.md

The wholes methods in the project must follow the doc update.

**Comment by wbeuil** [comment]
Wonder why we decided to put this issue in v0.8.0 since we will drop the old way of creating new resources.
