### ISSUE TITLE
Support .driftinclude and/or reconciling existing resources only

### ISSUE THREAD

**Issue by adamdonahue** [cloudskiff/driftctl#319]
**Description**
We just began importing our AWS objects (about 3000 of them) into Terraform.  Running a scan reports back thousands of objects, which we can always ignore, as work precedes, in order to only detect object drift for those we know have been modeled in Terraform.

But it might be more useful to either allow us to specify those in a `.driftinclude` file or to provide an option that does drIft analysis only on the objects modeled in the current `terraform.tfstate` object.  It won't pick up missing objects, but it would make migration a bit less noisy.

Just a thought.

**Comment by eliecharra** [comment]
Hi @adamdonahue thanks for your interest in driftctl.

Actually it overlaps a lot the responsibility of `terraform plan` command as it was previously said there https://github.com/cloudskiff/driftctl/discussions/272#discussioncomment-384830

The first goal of driftctl is to show you unmanaged resources that are outside the scope of your terraform code, so it is not very relevant for your migration usecase.

Why are you using driftctl instead of `terraform plan` ? Is there something missing in terraform plan ? What do you expect exactly ?

Let us know if we missed a usecase there.

**Comment by adamdonahue** [comment]
We liked the idea of a single tool we could run on a schedule as opposed to several terraform plan runs against various state files.  But that's a minor point.

**Comment by eliecharra** [comment]
> We liked the idea of a single tool we could run on a schedule as opposed to several terraform plan runs against various state files. But that's a minor point.

Got it, it can make sense from this point of view thanks for your feedback 🙏🏻

**Comment by adamdonahue** [comment]
I think another thing that could address the need would be supporting JMESPath filters in the .driftignore file (or perhaps a .driftfilters file).  We'll probably create that anyhow, and construct the command line from it.

This is a very useful tool -- just want to make it even more useful!

**Comment by adamdonahue** [comment]
On a side note, the usage is a little confusing:

```
      --filter string   JMESPath expression to filter on
                        Examples :
                          - Type == 'aws_s3_bucket' (will filter only s3 buckets)
                          - Type =='aws_s3_bucket && Id != 'my_bucket' (excludes s3 bucket 'my_bucket')
                          - Attr.Tags.Terraform == 'true' (include only resources that have Tag Terraform equal to 'true')
```

The first example says "filter", which is vague.  Filter in or filter out?

The second example is the opposite of what I'd expect -- my understanding is that any object that matches the rule is _excluded_ from (ignored during) the scan.  But this example seems to indicate it is an exclude, since it's filtering out anything that _isn't_ that particular bucket.  Likewise for the third example; I thought this would exclude anything that has the tag.

Perhaps I'm just confused about the semantics of the `--filter` parameter.

**Comment by adamdonahue** [comment]
I'm thinking the semantics are as follows:
```
  --filter string   JMESPath expression indicating which objects will be ignored during the scan
                        Examples :
                          - Type == 'aws_s3_bucket' (scan ignores all s3 buckets)
                          - Type =='aws_s3_bucket && Id != 'my_bucket' (scan ignores everything but my_bucket)
                          - Attr.Tags.Terraform == 'true' (scan ignores anything with a tag Terraform equal to true)
```

**Comment by adamdonahue** [comment]
Rereading the docs, I see that my understanding of `--filter` is incorrect.  This indicates which resources _to_ scan, not which resources to ignore.

I apologize for the confusion.  Under "Filter rules" in the documentation it doesn't actually say what filter does -- include or exclude.  Given it came right after .driftignore, and was specified as an alternative, I assumed it was an ignore filter.  It's actually an include filter.  Maybe a note clarifying this in the documentation would help?

**Comment by eliecharra** [comment]
> Rereading the docs, I see that my understanding of `--filter` is incorrect. This indicates which resources _to_ scan, not which resources to ignore. Under "Filter rules" in the documentation it doesn't actually say what filter does -- include or exclude. Given it came right after .driftignore, and was specified as an alternative, I assumed it was an ignore filter. It's actually an include filter. Maybe a note clarifying this in the documentation would help?

You are totally right, a note in documentation could be great, ping @wbeuil 

The description of the option need to be updated too as we are only talking about ignoring resources
`JMESPath expression indicating which objects will be ignored during the scan`
