### ISSUE TITLE
Support aws_eks_node_group

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#325]
cf https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group

User @BROMANDO COMMANDO upvoted this one on discord 2021/3/9

**Comment by mgarber-ops** [comment]
The only minor catch with this one is that there should be a way for drifctl to respect the lifecycle block for TF code so that external scaling changes aren't treated as drift (cluster autoscaler automatically scaling worker nodes)

**Comment by sundowndev** [comment]
blocked by #324
