### ISSUE TITLE
Detect & exclude unsupported Terraform versions 

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#340]
**Description**
As discussed https://github.com/cloudskiff/driftctl/discussions/334 - and documented [here](https://docs.driftctl.com/0.6.0/limitations/#terraform--providers-support).

It is expected that running driftctl against a terraform state generated by an unsupported version should not be possible and be reported clearly to the user.

In the case of multiple Terraform versions inside a set of tfstates, they should be ignored so at least some execution can happen. This is probably to combine with the future state exclusion feature. 

It's much harder to exclude states generated by unsupported providers since their version is not written in the terraform state. Reading the code would help for this.

**Examples**

Single state: 

```
$ grep terraform_version terraform.tfstate
    "terraform_version": "0.11.14",
$ driftctl scan
ERROR: terraform.tfstate was generated using v0.11.14 which is not supported.
Exiting...
```

Multiple states: 

```
$ grep terraform_version 1.tfstate
    "terraform_version": "0.11.14",
$ grep terraform_version 2.tfstate
    "terraform_version": "0.14.5",
$ grep terraform_version 3.tfstate
    "terraform_version": "0.13.1",
$ driftctl scan --from tfstate://./states/
ERROR: 1.tfstate was generated using v0.11.14 which is not supported.
Running driftctl with 2.tfstate and 3.tfstate 
```

In this case, all the resources from 1.tfstate will be seen as drifted, unless we find a way to minimally detect them and ignore them from the output.

**Comment by sjourdan** [comment]
As we're working towards supporting the AWS provider <v2, let's think about whether we really don't support the 0.11 state format. Maybe we do in fact.

- add some test cases for Terraform 0.11
- goal: support 0.11, and not below (no one talked to us about supporting 0.10 at this stage)

**Comment by sundowndev** [comment]
May be we can use go-version by hashicorp for this https://github.com/hashicorp/go-version

**Comment by sjourdan** [comment]
it works but UX-wise it's not super neat:

![image](https://user-images.githubusercontent.com/419121/117479933-358c2e80-af61-11eb-93ce-659217f5ce8b.png)

can we do some better formatting? (those were just 2 terraform.tfstate files with old versions in them)
