### ISSUE TITLE
Terraform AWS Provider v2 support

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#347]
**Description**

driftctl currently supports only v3 of the AWS Provider - many people still use v2.
Let's support it!

**Comment by vainkop** [comment]
@sjourdan any updates on that? I see that you have `Past due by 5 days` with `37% complete` for `v0.8.0` release in https://github.com/cloudskiff/driftctl/milestone/11 so do you have a more precise estimate for support of aws provider v2 in particular?

**Comment by sjourdan** [comment]
hey @vainkop! Thanks for your continued interest!

We added a much-needed bugfix release `v0.7.1` in the roadmap after a ton of feedback and some bugs that were more important to fix now than later. TBH it includes a lot of feedback and requests you already heard about during the Anton Babenko show!

So you´re right, it took much longer to release `v0.8.0` with v2/v3 AWS provider support. I think `v0.7.1` will be released by tomorrow (2021/4/9), so I also think `v0.8.0` will be available by the end of the month as the full team will work again on this, and hopefully, earlier.

Thank you for your patience :pray: !

**Comment by vainkop** [comment]
@eliecharra too bad you've moved that from v0.8.0 to v0.9.0 😞

**Comment by vainkop** [comment]
@sjourdan release v0.9.0 is here & no support for AWS provider v2 again? :(

**Comment by sjourdan** [comment]
hey @vainkop you're right, we're still hard at work on the major rewrite needed to do this properly, so we decided to ship a feature useful to some users (the .driftignore generator) and a couple of bug fixes first. 

The good news is that the very last resource we needed to rewrite is about to be merged. Then the testing phase of the pre-release will begin. 

The whole thing much bigger than expected, but it was definitely highly needed to support any provider version. 

I'll let you know when a pre-release build is ready if you want to try it before it's released to the public, as you seemed to have very interesting use cases. 

Thank you for your patience and support :pray:

**Comment by GeraldCrescione** [comment]
Hi @vainkop 
just doing a quick follow up on this one. With [the v0.10.0 release](https://github.com/cloudskiff/driftctl/releases/tag/v0.10.0) driftctl now supports any Terraform AWS provider version. Here's a [blog post](https://driftctl.com/how-to-use-driftctl-with-different-terraform-providers/) that relates to that.
