### ISSUE TITLE
Test goreleaser instead of combination of gox & gh-release

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#355]
**Description**

@sundowndev convinced us to try goreleaser :)

the auto changelog feature can be interesting.

**Examples**

- https://github.com/goreleaser/example

**Comment by eliecharra** [comment]
Sam just pushed a PR on dagger side https://github.com/dagger/dagger/pull/388

May be inspiring ?

**Comment by eliecharra** [comment]
This is now integrated, we created #894 to handle docker builds in a more efficient way
