### ISSUE TITLE
Fix broken link in unmanaged security groups

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#370]
**Description**
Fix broken link there https://github.com/cloudskiff/driftctl/blob/main/pkg/analyser/analyzer.go#L22 and point it to the documentation website.

**Comment by sjourdan** [comment]
LGTM

```
Found 9 resource(s)
 - 0% coverage
 - 0 covered by IaC
 - 9 not covered by IaC
 - 0 missing on cloud provider
 - 0/0 changed outside of IaC
You have unmanaged security group rules that could be false positives, find out more at https://docs.driftctl.com/0.7.0/limitations#terraform-resources
```

**Comment by eliecharra** [comment]
Maybe we need to change this link to point to `https://docs.driftctl.com/limitations` for and always up-to-date documentation. driftctl is gonna evolve and this link will be outdated

**Comment by sjourdan** [comment]
you're exactly right! opened #426 for this
