### ISSUE TITLE
Create a homebrew formula 

### ISSUE THREAD

**Issue by wbeuil** [cloudskiff/driftctl#39]
**Description**
To facilitate installation on macOS, we must create a homebrew formula.

**Example**
This will make our users install driftctl with:
```
brew install driftctl
```

**Comment by wbeuil** [comment]
We are now live on homebrew-core, Homebrew/homebrew-core/pull/68389

**Comment by mwarkentin** [comment]
@wbeuil not sure what's going on, I see the formula was merged into homebrew-core, but I'm having issues installing using brew:

```
❯ brew update
Already up-to-date.

❯ brew install driftctl
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "driftctl".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

Any idea what might be going on? Are other people installing through brew successfully?

**Comment by wbeuil** [comment]
Hello @mwarkentin can you show me the output of `brew info driftctl` please ?

**Comment by mwarkentin** [comment]
@wbeuil running `brew config` showed me the problem and I've fixed it. Looks like I'd submitted a small patch to homebrew-core a month or two ago and my local was still on that branch (so missing all master branch updates since including `driftctl`). Sorry for the bother!

**Comment by wbeuil** [comment]
Good to hear @mwarkentin ! Have a great week-end
