### ISSUE TITLE
Release driftctl to Arch User Repository

### ISSUE THREAD

**Issue by mastertinner** [cloudskiff/driftctl#405]
**Description**
It would be awesome if `driftctl` could be found in the [Arch User Repository](https://aur.archlinux.org/).

**Example**
I would suggest something like the following `PKGBUILD` (not tested):

```
# Maintainer: Lena Fuhrimann

pkgname=driftctl-bin
pkgver=0.7.0
pkgrel=1
pkgdesc="Detect, track and alert on infrastructure drift"
arch=(x86_64 i686)
url="https://github.com/cloudskiff/driftctl"
license=(Apache)
provides=(driftctl)
_src="${url}/releases/download/v${pkgver}/driftctl"
source_x86_64=("${_src}_linux_amd64")
source_i686=("${_src}_linux_386")
sha256sums_x86_64=('xxx')
sha256sums_i686=('xxx')

package() {
	local x86_64=amd64 i686=386
	install -Dm755 driftctl -t "${pkgdir}/usr/bin"
}
```

If you want, I can maintain it.

**Comment by eliecharra** [comment]
Thanks for this issue @mastertinner, as an Arch user I'm pretty enthusiast about it 😄 

> If you want, I can maintain it.

Thanks for your proposal 🙏🏻

Third party packaging is something we want to keep "official". I will try to work on it this week.

**Comment by eliecharra** [comment]
@mastertinner Just published `driftctl-bin` there https://aur.archlinux.org/packages/driftctl-bin/ if you wanna give it a try.

**Comment by mastertinner** [comment]
Works like a charm. Thanks a lot, @eliecharra!
