### ISSUE TITLE
Listing states from S3 can take time and make the progressbar timeout

### ISSUE THREAD

**Issue by moadibfr** [cloudskiff/driftctl#408]
**Description**
Listing states from S3 can take time and make the progressbar timeout

**How to reproduce**
Fill a bucket with a lot a files and run scan with this bucket in --from

**Possible Solution**
We should introduce a new progressbar for state enumeration count and one for resource enumeration from states files

**Comment by eliecharra** [comment]
@moadibfr I was wondering if the progressbar should be restarted automatically after a timeout if a new event occur. Sometime read actions may be slow but ends with a success after the timeout, for me we should show that something hang bit if it's ends with a success we should resume the spinning. WDYT @wbeuil we talked about it weeks ago in a pair session if I remember correctly 🤔 

For example :

```
State: Spinning
<-- No new events
State: Hanged after N seconds
<-- New event occur after the timeout
State: Spinning 
etc ...

```

**Comment by wbeuil** [comment]
I had the problem when testing driftctl with my Cloudflare DNS (thanks Orange). And it is indeed misleading to see that I hit the timeout, my requests succeed afterwards and the progress was not restarted. I agree with @eliecharra

**Comment by moadibfr** [comment]
If this happen we should set the timeout to a higher value. Timeout should happen if there is nothing happening.
I think the idea is to tell the user nothing is happening and he can quit so it should be an rare exception if this is not a real hang.

But yeah I think it could be a good idea to allow progressbar to get event even when timeouted and restart the render. So when we have this exception if the user wait enough it will still work.

**Comment by eliecharra** [comment]
> If this happen we should set the timeout to a higher value.

It's gonna be a never ending battle. Timeout can be relative to user setup (xDSL with latency line, issues with DNS like @wbeuil , etc ...)

> I think the idea is to tell the user nothing is happening and he can quit so it should be an rare exception if this is not a real hang.

I found this is very weak as we cannot predict any network latency or other issues that can slow down the process but does not mean there is an hang. I think it should be the user responsibility to take the decision to interrupt, our actual timeout should be there for UI/UX purpose only.

**Comment by moadibfr** [comment]
> It's gonna be a never ending battle. Timeout can be relative to user setup (xDSL with latency line, issues with DNS like @wbeuil , etc ...)
yeah but we should find a timeout value that make it as rare as possible

> I found this is very weak as we cannot predict any network latency or other issues that can slow down the process but does not mean there is an hang. I think it should be the user responsibility to take the decision to interrupt, our actual timeout should be there for UI/UX purpose only.
yeah but what's the ux purpose if it doesnt give any indication ? I think the indication should be " You waited a long time we thinks there is nothing happening anymore." Even if this mean that most user wait more time that they should. OFC there will be case where it don't work and it will be user's responsibility to kill or not. But we should find a value that's long enoght so most people don't see the progress bar stop.
But as I said it's still a good idea to allow it to restart if it timed out but it finally get an event after.

**Comment by eliecharra** [comment]
Progress bar resume handled there #420

**Comment by sundowndev** [comment]
> Progress bar resume handled there #420

@cloudskiff/engineering Should we close this in favor of #420 ?

**Comment by mwarkentin** [comment]
> Possible Solution
> We should introduce a new progressbar for state enumeration count and one for resource enumeration from states files

I did like the idea of this, if you have a large number of statefiles to be parsed or scanned it would be nice to see progress before the resources themselves begin to be scanned.

I think resuming the progress bar helps but they are slightly different (and both helpful) approaches to me.

**Comment by eliecharra** [comment]
> > Progress bar resume handled there #420
> 
> @cloudskiff/engineering Should we close this in favor of #420 ?

No, there is two distinct topics there. #420 is to fix a bug when progress bar does not resume after a timeout and this issue is to add a new progressbar for state enumeration and resources enumeration.

**Comment by sjourdan** [comment]
LGTM, very clear UX with 1000 states on an S3 located on the other side of the world. Takes like 2mn but keeps doing something. 

```
❯  LOG_LEVEL=error driftctl-0.8.0 scan --from tfstate+s3://a-bucket-filled-with-files/*.tfstate
Scanned states (1001)      
Scanned resources (57)      
[...]

```
