### ISSUE TITLE
.driftignore generator

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#415]
**Description**

As a new driftctl user
I want to generate a .driftignore file containing all my current drifts
So I can start fresh and get information about new drifts quickly, and fix my exiting ones later_

Goal: reformat the JSON output to a `type.name` schema that fits the `.driftignore`. 

## Mockup 2021/5/18

**User run 1:** 

This is the first driftctl run for the user, likely on a laptop or an interactive terminal. The user likely also already spent time finding the right environment variables, or tfstate locations.

This user discovers many drifts through the human-readable output of the CLI. 

When drift is detected, driftctl tells the user how to generate a .driftignore file so he can go to run 2.

```shell
$ driftctl scan --from tfstate+s3://mybucket/ 
Scanned states (1) 
Found resources not covered by IaC:
  aws_security_group:
    - sg-04bc6391da4b53075
[...]
Found 16 resource(s)
 - 18% coverage
 - 3 covered by IaC
 - 13 not covered by IaC
 - 0 missing on cloud provider
 - 0/3 changed outside of IaC
You have unmanaged security group rules that could be false positives, find out more at https://docs.driftctl.com/limitations

Hint: use driftctl gen-driftignore to generate a .driftignore file 
exit status 1
```

**User run 2:** 

In this run, the user will launch the command run 1 mentioned - and driftctl will show how to use it:

```shell
$ driftctl gen-driftignore
Error: to generate a .driftignore file, use driftctl gen-driftignore --from <drifts.json>
Generate a JSON using driftctl scan --output json://path/to/drifts.json
```

**User run 3:** 

In this run, the user will run the same command as the first, but with the JSON output as indicated in run 2.

```shell
$ driftctl scan --output json://drifts.json
Scanned states (1) 
Scanned resources  
$ file drifts.json 
drifts.json: JSON data
```

**User run 4:** 

In this run, the user finally generates the .driftignore file from the JSON output generated in run 3.

```shell 
$ driftctl gen-driftignore --from drifts.json 
# Resources not covered by IaC resources
aws_s3_bucket.example-1
aws_iam_access_key.AKIASXXX
[...]

$ driftctl gen-driftignore --from drifts.json > .driftignore

$ cat .driftignore
# Resources not covered by IaC resources
aws_s3_bucket.example-1
aws_iam_access_key.AKIASXXX
[...]
```

**User run 5:**

Final run: the user runs driftctl with an initial .driftignore file so he can get started.

```shell
$ driftctl scan --from tfstate+s3://mybucket/ 
Scanned states (1) 
Found 3 resource(s)    
 - 100% coverage
Congrats! Your infrastructure is fully in sync.
```

The user can now move on and get started in the second phase of his journey, like build his own docker image with the initial .driftignore file. 

<details>
  <summary>**Example (outdated)**</summary>

```shell
$ driftctl gen-driftignore --from tfstate+s3://mybucket-full-of-states/

Scanning resources: ⣟ (79) 
<- no analyze output there ->
Initial .driftignore file is generated.

$ cat .driftignore
# Resources not covered by IaC resources
aws_s3_bucket.example-1
aws_iam_access_key.AKIASXXX

# Missing resources
aws_iam_user.terraform
aws_iam_role_policy.cloudskiff_qa_test_role:qa_policy

# Changed resources
aws_iam_user.terraform
aws_iam_role_policy.cloudskiff_qa_test_role:qa_policy
aws_iam_policy_attachment.labs-arn:aws:iam::aws:policy/AdministratorAccess
```

</details>

**Comment by eliecharra** [comment]
@sjourdan What behavior do you expect if an existing `.driftignore` already exist ?

**Comment by sjourdan** [comment]
Good point!
KISS: we don´t overwrite and clean exit

```shell
$ driftctl scan --from tfstate+s3://mybucket-full-of-states/ --gen-driftignore
An existing .driftignore file is found. Please rename the existing one to generate a new one.
Exiting.
```

**Comment by sundowndev** [comment]
Isn't it better to parse the JSON output instead of performing a new scan?

Example :

```shell
$ driftctl scan --from tfstate+s3://mybucket-full-of-states/ -o json://stdout | driftctl gen-driftignore
```

I also though about just creating a new output : 

```shell
$ driftctl scan --from tfstate+s3://mybucket-full-of-states/ -o text://.driftignore

# Only ignore unmanaged resources
$ driftctl scan --from tfstate+s3://mybucket-full-of-states/ -o text://.driftignore --filter "Status=='unmanaged'"
```

WDYT @cloudskiff/engineering  ?

**Comment by eliecharra** [comment]
@sundowndev I think it totally makes sense since we dont want to duplicate every flag parameter for `gen-driftignore` cmd.

The second approach (new output) makes the feature less obvious to use IMHO, not a big fan.

I prefer the first approach since it is a better separation of concern and keep thinks independent.

**Comment by adamdonahue** [comment]
How about just sending the output to `stdout`?

**Comment by sundowndev** [comment]
> How about just sending the output to `stdout`?

@adamdonahue Can you elaborate about why do you think it makes sense to send output to stdout ? As this is intended for users with complex use cases and tons of resources, sending output to stdout would imply they'd have to copy/paste the entire thing by themselves. I don't think that's what we want since this feature is supposed to remove the pain of dealing with those resources.

**Comment by eliecharra** [comment]
You can still pipe the output in a file without the need to copy/paste.

> driftctl scan --from tfstate+s3://mybucket-full-of-states/ -o json://stdout | driftctl gen-driftignore > .driftignore

**Comment by sundowndev** [comment]
> You can still pipe the output in a file without the need to copy/paste.
> 
> > driftctl scan --from tfstate+s3://mybucket-full-of-states/ -o json://stdout | driftctl gen-driftignore > .driftignore

@eliecharra I though the goal was to put the content in the file directly, not sending output to stdout. I'll update my changes in #433 then

**Comment by sundowndev** [comment]
> You can still pipe the output in a file without the need to copy/paste.
> 
> > driftctl scan --from tfstate+s3://mybucket-full-of-states/ -o json://stdout | driftctl gen-driftignore > .driftignore

I mean why not. I was just wondering if there was a particular use case behind that request. I'll let reviewers tell me what approach we should prefer on my PR.

**Comment by sundowndev** [comment]
> or something more explicit right from the `driftctl` help output.

@sjourdan You should see more info by typing `driftctl gen-driftignore -h`. Does that make it clearer ? We also added an example in the code but for some reason it's not displayed in the CLI (https://github.com/cloudskiff/driftctl/blob/v0.8/pkg/cmd/gen_driftignore.go#L19).

```
This command will generate a new .driftignore file containing your current drifts and send output to /dev/stdout

Usage: driftctl gen-driftignore [flags]

FLAGS:
      --exclude-changed     Exclude resources that changed on cloud provider
      --exclude-missing     Exclude missing resources
      --exclude-unmanaged   Exclude resources not managed by IaC
  -f, --from string         Input where the JSON should be parsed (default "/dev/stdin")

INHERITED FLAGS:
      --disable-telemetry   Disable telemetry
  -h, --help                Display help for command
      --no-version-check    Disable the version check
      --send-crash-report   Enable error reporting. Crash data will be sent to us via Sentry.
                            WARNING: may leak sensitive data (please read the documentation for more details)
                            This flag should be used only if an error occurs during execution
```

**Comment by adamdonahue** [comment]
> > You can still pipe the output in a file without the need to copy/paste.
> > > driftctl scan --from tfstate+s3://mybucket-full-of-states/ -o json://stdout | driftctl gen-driftignore > .driftignore
> 
> I mean why not. I was just wondering if there was a particular use case behind that request. I'll let reviewers tell me what approach we should prefer on my PR.

Generally it's just a best practice to use stdout, and give the user control over where things are written or how output is manipulated using output redirects and pipelines, respectively.

What you don't get with `-o` is the ability to directly `grep` etc., right from the command line:

`driftctl scan .... | grep something > /tmp/myoutput`

or some such.

**Comment by sjourdan** [comment]
LGTM, easy enough and working as expected: 

```shell
# First create a JSON output
❯  ~/bin/driftctl-0.9.0 scan --from tfstate://**/*.tfstate --output json://drifts.json
Scanned states (4) 
Scanned resources (62)      

# Then generate the driftignore file from it
❯  ~/bin/driftctl-0.9.0 gen-driftignore -i drifts.json > .driftignore 

# Voila!
❯  ~/bin/driftctl-0.9.0 scan --from tfstate://**/*.tfstate
Scanned states (4) 
Scanned resources (62)      
Found 1 resource(s)
 - 100% coverage
Congrats! Your infrastructure is fully in sync.
```

**Comment by GeraldCrescione** [comment]
Hey @adamdonahue 
Just a quick follow up on this one. Thanks a lot for your comments on the driftignore generator. Did you get a chance to give it a whirl? There's a "How To" blog post related to it btw https://driftctl.com/how-to-generate-driftignore-and-track-drift-from-clean-state/
