### ISSUE TITLE
guess region from provider configuration(s) by default

### ISSUE THREAD

**Issue by levequej** [cloudskiff/driftctl#418]
**Description**
Hi,

When I do a driftctl scan, it uses my ~/.aws/config default region and does not check the region configured in the aws provider from the .tf ( I think this should be the sane default)

**Example**

default region in my ~/.aws/config  is eu-west-1 .I want to do a driftctl scan with  the following 

```terraform
provider "aws" {
  profile = "default"
  region  = "eu-west-3"
}
```

My problem is that it's gonna check eu-west-1 and not eu-west-3. If I change the region in my profile to eu-west-3, then driftctl scan works as expected.

Tested using terraform 0.14.10 and drifctl 0.7.10 on windows 10 (with git-bash) .

It's related to #88 , I also wonder if it would make sense to check the .tf conf rather than the state.

**Comment by sjourdan** [comment]
hey @levequej! Definitely related to #88 - whether driftctl should read the code or the state, the intention, or the last known reality. 

I believe that in your case, you'd rather read the code than the state? 

It would help a lot if you could describe quickly your intended workflow using the code! :pray:

**Comment by levequej** [comment]
Hi @sjourdan ,

In my case it's mostly read the region  from the tf code (aws provider configuration) rather than from the state but I also  think it would be nice to be able to detect a (maybe unvoluntary) region change (diff region from state vs region in .tf).

The use case would be for an organization with mutiple regions to be able to automatically select the proper region from within the aws provider configuration in terraform, and also to be able to detect region misconfiguration which would cause to have stuff instantiated in the wrong region (and maybe stay undetected and cost $$$ for nothing).
