### ISSUE TITLE
Display instance name when tag name exist

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#419]
**Description**
We should display the instance name for `aws_ec2_instance` and other resource that use tags for a name.

**References**:
- https://d1.awsstatic.com/whitepapers/aws-tagging-best-practices.pdf (page 13)

**Comment by sjourdan** [comment]
LGTM!
Not sure it's extensive, but the `aws_instance` works indeed.
```
Found resources not covered by IaC:
[...]
  aws_instance:
    - i-0a85fc94dad0eee9a (Name: aws-www-1)
[...]
```
