### ISSUE TITLE
We should cache resources enumeration

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#421]
**Description**
Sometimes we enumerate multiple time the same kind of resource, for example S3 buckets enumeration is done in  `S3BucketMetricSupplier`, etc ...
We want to cache resources enumeration in the repository layer.
It will also ensure atomicity during a scan for AWS endpoints that have inconsistency.

**Technical details**
We want to have a global cache mechanism that is used in multiple repositories.
We want to use the caching layer only for resources that are enumerated multiple time.

**Comment by sjourdan** [comment]
looks very trustable to me :)
