### ISSUE TITLE
using `--error-reporting` alone sends a useless report

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#423]
**Description**

Maybe there's no point in sending an empty sentry report when someone simply enables error reporting for testing

```
$ driftctl --error-reporting 
Detect, track and alert on infrastructure drift.

Usage: driftctl <command> [flags]

COMMANDS:
  completion               Generate completion script
  scan                     Scan
  version                  Display driftctl version

FLAGS:
      --error-reporting    Enable error reporting.
                           WARNING: may leak sensitive data
  -h, --help               Display help for command
      --no-version-check   Disable the version check

LEARN MORE:
  Use "driftctl <command> --help" for more information about a command
Sending error report ... done, thank you ❤️
```

**Environment**
 - OS: fedora 33
 - driftctl version: 0.7.0
 
**How to reproduce**

**Possible Solution**

Maybe do not send the report automatically if there´s nothing to send, or no command used

**Additional context**

**Comment by eliecharra** [comment]
@sjourdan Nothing is really sent if no crash happened.

We cannot know if something was captured by sentry, so maybe we can remove this message ?

**Comment by lotoussa** [comment]
Actually, with the v0.7.1 this flag behaviour is different.

**Comment by eliecharra** [comment]
> Actually, with the v0.7.1 this flag behaviour is different.

The flag name has changed but the behavior remain the same

**Comment by lotoussa** [comment]
> > Actually, with the v0.7.1 this flag behaviour is different.
> 
> The flag name has changed but the behavior remain the same

`./bin/driftctl_darwin_amd64 --send-crash-report
Detect, track and alert on infrastructure drift.

Usage: driftctl <command> [flags]

COMMANDS:
  completion               Generate completion script
  scan                     Scan
  version                  Display driftctl version

FLAGS:
  -h, --help                Display help for command
      --no-version-check    Disable the version check
      --send-crash-report   Enable error reporting. Crash data will be sent to us via Sentry.
                            WARNING: may leak sensitive data (please read documentation for more details)
                            This flag should be used only if an error occur during execution

LEARN MORE:
  Use "driftctl <command> --help" for more information about a command`
  
For example i'm talking about the message in your previous discussion with sjourdan

**Comment by eliecharra** [comment]
This is a bug that will be fixed with https://github.com/cloudskiff/driftctl/pull/424

**Comment by sundowndev** [comment]
> @sjourdan Nothing is really sent if no crash happened.
> 
> We cannot know if something was captured by sentry, so maybe we can remove this message ?

@eliecharra May be we could replace this with a debug message ? I'll push a PR about that.
