### ISSUE TITLE
Support for Terraform Enterprise/Cloud

### ISSUE THREAD

**Issue by kmai** [cloudskiff/driftctl#434]
**Description**
Currently, you can retrieve the `terraform.tfstate` file from S3, which is great. But what if we use Terraform Enterprise or Terraform Cloud? I haven't found any issues related to this feature, or documentation. Not even a mention in the `driftctl` help.

**Example**
For example, we're currently supporting:

* `tfstate://`: Local
* `tfstate+s3://`: S3
* `tfstate+http://`: HTTP Endpoint
* `tfstate+https://`: HTTPS Endpoint

This feature request would also implement something like `tfstate+tfcloud://` and/or `tfstate+enterprise://`.

**Comment by wbeuil** [comment]
Hello @kmai, thanks for opening this issue.

I only tested with terraform cloud, thus I can't talk about terraform enterprise but for now you can use driftctl like this:

```
# First, use Terraform API to request the hosted-state-download-url
$ curl \
  --header "Authorization: Bearer $TOKEN" \
  --header "Content-Type: application/vnd.api+json" \
https://app.terraform.io/api/v2/workspaces/$WORKSPACE_ID/current-state-version

# Then, use driftctl with the https endpoint
$ driftctl scan --from tfstate+https://<hosted-state-download-url>
```

Would it fit your use case at this moment ?

**Comment by kmai** [comment]
Hey! Thanks for the follow up. 

I tried that approach and it works, but it'd be amazing to have the support for it a bit more transparent. It is a bit more hacky than expected and it's not documented either.

I think that this and https://github.com/cloudskiff/driftctl/issues/53 are on my wishlist, but so far, this is a really cool tool.

I can't wait to implement it!

**Comment by eliecharra** [comment]
Hey @ayshiff we are always open to contributions 🙏🏻 You can join us on discord our #dev channel if you want additional details and if you want to discuss about implementation details

**Comment by nikolay** [comment]
How will this works if you have your infrastructure broken into multiple TFC workspaces?

**Comment by sundowndev** [comment]
> How will this works if you have your infrastructure broken into multiple TFC workspaces?

@nikolay You can specify multiple state files for a single scan, as long as you can have a single TFC token for multiple workspaces. I'm not a TFC user so may be I miss something, but it should be possible like so: 

```shell
$ TFC_TOKEN=xxx \
  driftctl scan --from tfstate+tfcloud://<workspace_id> --from tfstate+tfcloud://<workspace_id>
```

**Comment by sjourdan** [comment]
LGTM! Awesome contribution @ayshiff :pray: 

```
❯  driftctl-0.8.0 scan --from tfstate+tfcloud://ws-L4dG719GPU9FP6Nj/ --tfc-token $TFC_TOKEN
Scanned states (1)      
Scanned resources (57)      
Found resources not covered by IaC:
  aws_s3_bucket:
    - yaddi.yadda
Found 2 resource(s)
 - 50% coverage
 - 1 covered by IaC
 - 1 not covered by IaC
 - 0 missing on cloud provider
 - 0/1 changed outside of IaC

```

I used the documentation PR as a basis for following configuration as a user (https://github.com/cloudskiff/driftctl-docs/pull/47/files)
