### ISSUE TITLE
clarify how to add some resources to the .driftignore file

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#439]
**Description**

Take this simple driftctl output: 

```shell 
$ driftctl scan 
Scanned resources:    (55)
Found resources not covered by IaC:
  aws_iam_user:
    - terraform
  aws_security_group_rule:
    - Type: ingress, SecurityGroup: sg-0ce251e7ce328547d, Protocol: tcp, Ports: 5432, Source: 96.202.220.106/32
  aws_sqs_queue:
    - https://sqs.us-east-1.amazonaws.com/141177182257/queue-6qaidu.fifo
  aws_lambda_event_source_mapping:
    - Source: arn:aws:sqs:us-east-1:141177182257:queue-6qaidu.fifo Dest: arn:aws:lambda:us-east-1:141177182257:function:lk6n03-lambda-demo

```

Let's say I want to add all those resources to the `.driftignore`. 

It's easy to infer from the output that adding `aws_iam_user.terraform` to the `.driftignore` file will work (and it does)

For the `aws_sqs_queue`, it's quite straightforward reading the [related documentation](https://docs.driftctl.com/0.7.1/usage/filtering/driftignore): (`aws_sqs_queue.https://sqs\.us-east-1\.amazonaws\.com/141177182257/queue-6qaidu\.fifo`) 

But what is the user supposed to ignore with the `aws_security_group_rule` or `aws_lambda_event_source_mapping` output?

**Environment**
 - OS: fedora 33
 - driftctl version: 0.7.1

**How to reproduce**

**Possible Solution**

**Additional context**

**Comment by eliecharra** [comment]
We should always display IDs for every resource for ignore purpose and document this

**Comment by sjourdan** [comment]
LGTM! Timely to test and confirm IDs from another issue:

```
Found missing resources:
  aws_kms_alias:
    - alias/key-alias
  aws_kms_key:
    - e492d07f-0201-4346-a33b-727454d0787b
```
