### ISSUE TITLE
Add telemetry

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#441]
**Description**
To be able to understand our user usecases, context and help us prioritize features we want to add a telemetry feature to send us anonymous data.

- [x] Document data sent when telemetry is active
- [x] Create telemetry lambda
- [x] Collect data after the run and add a opt-out flag and env var

**Example**
- how many resources were scanned (total_resources=2345)
- how many resources were actually managed by Terraform (managed_resources=150)

**Reference**
- https://github.com/cloudskiff/driftctl/discussions/343#discussioncomment-616124

**Comment by eliecharra** [comment]
Telemetry endpoint now available there 

```
POST https://2lvzgmrf2e.execute-api.eu-west-3.amazonaws.com/telemetry
Content-Type: application/json
{
    "total_resources": 123,
    "total_managed": 12
}
```

**Comment by sjourdan** [comment]
LGTM

I confirm that 

- setting `DCTL_DISABLE_TELEMETRY=true` didn't send any information (I used a new public ipv4 to prove that)
- setting the env var to false sent the basic anonymous information 

![image](https://user-images.githubusercontent.com/419121/117497653-0da8c500-af79-11eb-9f66-ad94c039abc0.png)
