### ISSUE TITLE
Add execution time to telemetry

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#442]
**Description**
Following #441, we want to add the execution duration (in seconds) to telemetry.
It should include state enumeration, resource enumeration from the states, and remote enumeration.

**Comment by sjourdan** [comment]
LGTM, definitely my test case

![image](https://user-images.githubusercontent.com/419121/117498975-d3402780-af7a-11eb-99bd-ff4ccd5c86dc.png)
