### ISSUE TITLE
Enable drift detection on `aws_instance` shutdown behavior

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#446]
**Description**
Following https://github.com/cloudskiff/driftctl/issues/403, we should think about removing the workaround for newest provider version as this is now fixed on terraform provider side.

**Possible Solution**
We should find a way to fetch the terraform provider version and compare semver version to disable the fix for provider version > `3.38.0`

**Comment by sjourdan** [comment]
@eliecharra says: 

_Elie: @Stephane Small precision about this issue https://github.com/cloudskiff/driftctl/issues/446 (how to test it). First create an instance with tf with a provider version <= 3.38. then manually change shutdown behavior in the console => no drift should be detected. Try with a provider version > 3.38 and then it should be detected. Then rollback to the good value from the console => no drift should happen_

**Comment by sjourdan** [comment]
LGTM! 

Detected: 

```
  Name: "vm-1"
} (computed)
        + throughput: <nil> => 0 (computed)
    - i-0cb27ba2d1fb8312d (aws_instance):
        + capacity_reservation_specification: <nil> => [map[capacity_reservation_preference:open]]
        ~ instance_initiated_shutdown_behavior: "" => "terminate" (computed)
        + tags_all: <nil> => {
  Name: "vm-1",
  Terraform: "true",
  Environment: "dev"
} (computed)

```

No detected: 

```
  Name: "vm-1"
} (computed)
        + throughput: <nil> => 0 (computed)
```

(the false positive is https://github.com/cloudskiff/driftctl/issues/612)
