### ISSUE TITLE
Filtering should be considered prior to scans 

### ISSUE THREAD

**Issue by jackson-theisen-bind** [cloudskiff/driftctl#456]
**Description**
When using filter rules, a scan still tries to look at resources that should be filtered. 

**Environment**
 - OS: macOS 
 - driftctl version: `v0.7.1` 

**How to reproduce**

Create an ec2 instance, remove the ec2 actions from https://docs.driftctl.com/0.7.1/providers/aws/authentication/#least-privileged-policy on the driftctl user's policy, then perform a scan with a filter to exclude ec2 instances:
```
$ driftctl scan --from tfstate+s3://foo/bar  --filter 'Type!="aws_instance"'
ERRO[0010] Unable to decode resource from state name=instance type=aws_instance
```

**Possible Solution**

Rewrite the logic so filtering occurs prior to a scan, not just against the results. 

**Additional context**

**Comment by eliecharra** [comment]
Hi @jackson-theisen-bind thanks for your interest in driftctl 🙏🏻 

This is something we have in mind for the next releases since a couple of weeks. It will also lead to performance and rate limit optimization.

We currently have a lot of work in progress for `v0.8.0` and `v0.9.0` (a big core refactoring is in progress) so we do not have a deadline for now, but it will probably be the next big feature we'll work on.

**Comment by sjourdan** [comment]
This is also linked to a correct realization of https://github.com/cloudskiff/driftctl/issues/468

**Comment by eliecharra** [comment]
This is currently blocked by deep mode

**Comment by eliecharra** [comment]
We will work on it but only with driftignore compatibility.

**Comment by sjourdan** [comment]
LGTM

Nothing is scanned with a `driftignore` ignoring everything. 

- < 2s with 0.14
- > 8s with 0.13

```sh
❯  driftctl version
v0.13.0
❯  time driftctl scan --output json://stdout 
{
        "summary": {
                "total_resources": 0,
                "total_changed": 0,
                "total_unmanaged": 0,
                "total_missing": 0,
                "total_managed": 0
        },
        "managed": null,
        "unmanaged": null,
        "missing": null,
        "differences": null,
        "coverage": 0,
        "alerts": null
}
real    0m7.882s
user    0m1.036s
sys     0m0.201s


❯  time LOG_LEVEL=error driftctl-pre scan --output json://stdout 
{
        "summary": {
                "total_resources": 0,
                "total_changed": 0,
                "total_unmanaged": 0,
                "total_missing": 0,
                "total_managed": 0
        },
        "managed": null,
        "unmanaged": null,
        "missing": null,
        "differences": null,
        "coverage": 0,
        "alerts": null,
        "provider_name": "aws",
        "provider_version": "3.46.0"
}
real    0m1.736s
user    0m0.740s
sys     0m0.088s
```

On another example, the proof is that driftctl is actually scanning an unauthorized S3 bucket while only ECR is configured in `.driftignore`: 

```sh
❯  cat .driftignore
*
!aws_ecr_repository
```

**Using 0.13** 

```sh 
❯  time LOG_LEVEL=error driftctl scan 
Scanned states (1) 
AccessDenied: Access Denied
        status code: 403, request id: 7S6SKHRENVHZWQRW, host id: ujYFqy1M39H3Ana9Vdq/ty0XT533sAWVWNfeyev+eqlr7XO9yqH8cZwaq4GD+8IrkSdA+KSCVJA=

real    0m4.947s
user    0m1.080s
sys     0m0.190s
``` 

**Using 0.14**

```sh
❯  time LOG_LEVEL=error driftctl-pre scan 
Scanned states (1) 
Found 100 resource(s)  
 - 100% coverage
Congrats! Your infrastructure is fully in sync.
Scan duration: 1s
Provider version used to scan: 3.46.0. Use --tf-provider-version to use another version.

real    0m2.060s
user    0m0.802s
sys     0m0.106s
```
