### ISSUE TITLE
driftctl should report when no tfstate found on S3

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#461]
**Description**

As a user, when I `driftctl scan` using an S3 bucket with no tfstate in it, I expect at least a warning or an error - certainly not the tool going on as if everything was smooth.

**Environment**
 - OS: Fedora 34
 - driftctl version: 0.7.1

**How to reproduce**

1. create an empty S3 bucket
2. run driftctl scan --from tfstate+s3://my-empty-bucket/
3. confirm a scan happened fully, even without no tfstate found

**Possible Solution**

```shell 
$ driftctl scan --from tfstate+s3://mybucket/ 
No Terraform states found on s3://mybucket, exiting
```

**Additional context**

Bug found by @sundowndev :)

Locally it's less bizarre - even if it's not super user-friendly: `lstat terraform.tfstate: no such file or directory`.

**Comment by sundowndev** [comment]
For the record, I think this should be done for all enumerators here https://github.com/cloudskiff/driftctl/blob/main/pkg/iac/terraform/state/terraform_state_reader.go#L238

**Comment by sjourdan** [comment]
LGTM 

```
❯  AWS_PROFILE="cloudskiff-demo" LOG_LEVEL=critical driftctl-0.10.0 --tf-provider-version=3.44.0 scan --from tfstate+s3://dctl-461-nostate/**/*.tfstate
Scanned states (0)      
no Terraform state was found in dctl-461-nostate/**/*.tfstate, exiting
```

This is a bit at odds with #623 though. Let's think about the feature again.
