### ISSUE TITLE
Should ignore default aws_db_subnet_group if there is one

### ISSUE THREAD

**Issue by wbeuil** [cloudskiff/driftctl#462]
**Description**
Found that after creating 2 new aws_db_subnet_group, driftctl output me 2 managed resources and 1 unmanaged resource which is the default one. We should ignore this noise.

```tf
resource "aws_vpc" "vpc" {
    cidr_block = "10.1.0.0/16"
}

resource "aws_subnet" "subnet1" {
    vpc_id = aws_vpc.vpc.id
    cidr_block = "10.1.0.0/24"
}

resource "aws_subnet" "subnet2" {
    vpc_id = aws_vpc.vpc.id
    cidr_block = "10.1.1.0/24"
}

resource "aws_subnet" "subnet3" {
    vpc_id = aws_vpc.vpc.id
    cidr_block = "10.1.2.0/24"
}

resource "aws_subnet" "subnet4" {
    vpc_id = aws_vpc.vpc.id
    cidr_block = "10.1.3.0/24"
}

resource "aws_db_subnet_group" "foo" {
    name       = "foo"
    subnet_ids = [aws_subnet.subnet1.id, aws_subnet.subnet2.id]
}

resource "aws_db_subnet_group" "bar" {
    name_prefix       = "bar"
    subnet_ids = [aws_subnet.subnet3.id, aws_subnet.subnet4.id]
}
```

![image](https://user-images.githubusercontent.com/8110579/116238452-a3ff0e80-a761-11eb-8632-bc61a69e4a43.png)

**Comment by sjourdan** [comment]
a default db subnet group is created automatically by the ["db instance" resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance). 

exactly like a route53 zone creates a couple of records (SOA...)

And driftctl ignores those records. 

Should driftctl ignore too the automatically created db_subnet_group? 

I don't think so. I expect db_subnet_group to be reintegrated in the tf code at some point. This is too important.

WDYT?
