### ISSUE TITLE
.driftignore file support in CLI usage for docker doc

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#47]
**Description**

We don't describe how to optionally share the `.driftignore` file when using driftctl on docker from a repo.

Something like this: 

```
$ docker run -it --rm -v ~/.aws:/app/.aws:ro -e AWS_RE
GION=eu-west-3  -v $(pwd)/.driftignore:/app/.driftignore -v $(pwd)/terraform.tfstate:/app/terraform.tfstate:ro   -v ~/.d
riftctl:/app/.driftctl   -e AWS_PROFILE=cloudskiff-demo   cloudskiff/driftctl:v0.1.1 --no-version-check scan
Scanning AWS on region: eu-west-3
Found 4 resource(s)
 - 100% coverage
```

**Comment by sjourdan** [comment]
@eliecharra you asked the original bug report: https://github.com/docker/for-win/issues/4812

**Comment by sjourdan** [comment]
The docker run we currently suggest is the following: 

```
docker run \
  -v ~/.aws:/app/.aws:ro \
  -v $(pwd)/terraform.tfstate:/app/terraform.tfstate:ro \
  -v ~/.driftctl:/app/.driftctl \
  -e AWS_REGION=us-east-1 \
  -e AWS_PROFILE=cloudskiff \
  cloudskiff/driftctl:v0.1.1 scan ## with the same option as the binary version
```

This won't work if we simply suggest to mount `-v $(pwd):/app:ro`, as we also need the `.aws` folder inside the same `/app` (for the AWS_PROFILE stuff). And we also need the `.driftctl` folder to be writeable to store the terraform aws provider. 
Our image doesn't include a shell nor a user home dir. 

Moving the AWS configuration to a non-standard dir would add useless complexity for our users ([AWS Doc](https://docs.aws.amazon.com/credref/latest/refdocs/file-location.html)) 

So in the end what we need for a universally simple developer experience: 

- the `~/.aws` _local_ folder mounted in the _container_ home as ro (currently `/app`)
- the current _local_ folder containing the state (if there's a state!) mounted somewhere like `/tf` in the _container_ as ro
- the _local_  `~/.driftctl` folder mounted as rw in the _container_ as rw

So a current working equivalent would look like: 

```bash
$ docker run -it --rm \
    -v ~/.aws:/app/.aws:ro \
    -v $(pwd)/:/tf:ro \
    -v ~/.driftctl:/app/.driftctl \
    -e DCTL_FROM=tfstate:///tf/terraform.tfstate \
    -e AWS_PROFILE=cloudskiff \
    cloudskiff/driftctl:v0.1.1 scan
```

it works but doesn't it make it a bit too complicated for a simple use case?

**Comment by eliecharra** [comment]
@sjourdan Nice catch, thanks for the feedback, I suggest to split HOME and working dir, we could have simpler like

```
docker run -it --rm \
    -v ~/.aws:/home/.aws:ro \
    -v $(pwd):/app:ro \
    -e DCTL_FROM=tfstate://terraform.tfstate \
    -e AWS_PROFILE=cloudskiff \
    cloudskiff/driftctl:v0.1.1 scan
```

We need to make env HOME pointing to /home for the above cmd to work, you could try by updating the Dockerfile.
