### ISSUE TITLE
difference between "scanned resources: x" and "found y resources" should be explained

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#476]
**Description**

Reported by multiple users as a worrying experience. 

At the beginning of a scan: 
![image](https://user-images.githubusercontent.com/419121/116694439-9646c480-a9bf-11eb-8888-c3919ce62dee.png)

At the end of a scan:

![image](https://user-images.githubusercontent.com/419121/116694474-a1015980-a9bf-11eb-9be0-7682698885cf.png)

The total number of scanned resources is not the same as the one "found". 

Reason includes resources ignored, filtered, or internally processed. 

Still: it's not clear and generates user FUD.

**Solution**
Remove the resource count from the progress bar

**Comment by sundowndev** [comment]
I am not sure about the solution on this one.

- **Remove the resource count from the progress bar** : quick and easy, but we loose a bit of UX when it comes to scan large infrastructures. User might think the scan is stuck or loading forever, the count was indicating it's not the case.
- **Rethink wording** : The confusing part here is words we use to tell the user what the tool is doing. May be we need to replace those word so the user better understand that we *found* N resources, but we actually *analyzed* N resources. We can also add statements about that in the docs.

WDYT @cloudskiff/engineering ?

**Comment by eliecharra** [comment]
@sundowndev We agreed on counter removal in the latest planning

**Comment by sundowndev** [comment]
> @sundowndev We agreed on counter removal in the latest planning

Yes, but as I dug into this issue I realized the counter removal might create another UX issue. If it doesn't seem relevant to you then it's fine for me to just remove the counter as discussed.

**Comment by eliecharra** [comment]
> User might think the scan is stuck or loading forever, the count was indicating it's not the case.

We still got the spinner so this is fine

**Comment by sjourdan** [comment]
LGTM! 

- spinner is spinning
- recap at the end is consistent

```
❯  AWS_PROFILE="driftctl-role" LOG_LEVEL=critical driftctl-0.10.0 --tf-provider-version=3.44.0 scan --from tfstate://states/**/*.tfstateScanned states (3) 
[...]
Found 48 resource(s)
 - 6% coverage
 - 3 covered by IaC
 - 39 not covered by IaC
 - 6 missing on cloud provider
 - 1/3 changed outside of IaC
```
