### ISSUE TITLE
Scanning a dir using HTTP backend outputs an error

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#494]
**Description**

Scanning an empty dir with an HTTP backend should output something clean and meaningful to the user, as we do for other errors!

**Environment**
 - OS: fedora 34
 - driftctl version: 0.8.0 (pre)

**How to reproduce**

Inside an HTTP served directory, create some folder: 

```
mkdir bogus-dir
```

Then request this folder with driftctl 

```
  LOG_LEVEL=error driftctl-0.8.0 scan --from tfstate+https://***.com/bogus-dir/
Scanned states (1)      
2 problems:

- Unsupported state file format: The state file could not be parsed as JSON: syntax error at byte offset 1.
- Unsupported state file format: The state file does not have a "version" attribute, which is required to identify the format version.

```

**Possible Solution**

**Additional context**

**Comment by sjourdan** [comment]
Context: a user wants to load all the tfstates from a remote directory available through HTTP
Problem: maybe the user mistypes the folder name, or gives an empty folder name
Driftctl UX problem: instead of telling the user we didn't find any readable state file, we tell him about syntax errors and wrong formats (which are not helpful for the user to find his own issue)

Idea as mentioned in the original issue: 

```
$ driftctl-0.8.0 scan --from tfstate+https://***.com/bogus-dir/
Scanned states (1)      
1 problem:

- No Terraform state file found in the specified directory.
```

**Comment by AzySir** [comment]
Suggestion also for this, add a `--skips-if-no-state` type of flag. As I'm waiting for other devs to create statefiles but the buckets may exist so I can code in parallel. 

_(Work around for this is an empty .tfstate, however I believe that still leads to a fail)_

**Comment by sjourdan** [comment]
confirmed ok in 0.9.1 and 0.10.0-pre

```
❯  DCTL_TF_PROVIDER_VERSION="3.44.0" AWS_REGION="eu-west-3" AWS_PROFILE="cloudskiff-demo" driftctl-0.10.0 scan --from tfstate+https://driftctl.com/bogus/
Scanned states (1)      
Failed to read state file: The state file could not be read: error requesting HTTP(s) backend state: status code: 404
``` 

@AzySir I referenced your initial suggestion in the issue that is more likely to solve your use-case https://github.com/cloudskiff/driftctl/issues/623#issuecomment-864073056
