### ISSUE TITLE
False drift for some lambda function empty string field

### ISSUE THREAD

**Issue by moadibfr** [cloudskiff/driftctl#5]
**Description**
Some fields introduced by provider update are not normalized correctly (it seems the state is not always consistent depending if it's refreshed or not)
```
  - foo (aws_lambda_function):
    ~ ImageUri: <nil> => ""
    ~ SigningJobArn: <nil> => ""
    ~ SigningProfileVersionArn: <nil> => ""
```

**Environment**
 - OS: linux
 - driftctl version: 0.1.0

**How to reproduce**
Terraform code in lambda function supplier test help reproduce this.
Launch driftctl before and after a terraform refresh. The refreshed run show a drift.

**Possible Solution**
We should apply the same normalization from state and remote

**Comment by sjourdan** [comment]
running 0.1.1 against our own lambdas (on TF 0.13.5, not 0.14.2) I see this drift, is it related? 

```
Found drifted resources:
  - driftctl-version (aws_lambda_function):
    ~ LastModified: "2020-11-25T13:50:24.157+0000" => "2020-12-14T15:18:34.926+0000"
    ~ PackageType: <nil> => "Zip"
    ~ Environment.0.Variables.LATEST_VERSION: "v0.0.10" => "v0.1.1"
```

**Comment by eliecharra** [comment]
@sjourdan It is not related, drift you are seeing is an expected behaviour.

Typically a case to be handled by resource field ignore which is in progress in #28
