### ISSUE TITLE
CharacterSetName from aws_db_instance false positive

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#542]
**Description**

This should not be detected as a drift:

```
  - xxx (aws_db_instance):
    ~ CharacterSetName: "" => <nil> (computed)
```

**Environment**
 - OS:
 - driftctl version: 0.8.0

**How to reproduce**

**Possible Solution**

**Additional context**

Reported by staggerlee011 on Discord

**Comment by eliecharra** [comment]
Is it OK in the latest version ?

**Comment by wbeuil** [comment]
Yes it is in the `v0.9.0`
