### ISSUE TITLE
Display elapsed time at end of scan

### ISSUE THREAD

**Issue by sundowndev** [cloudskiff/driftctl#550]
**Description**
We already measure scan duration in telemetry, but we don't display it to the end-user. As a user, I find it useful to know how much time it took for the tool to perform an analysis of my entire infrastructure. This tiny UX improvement would also highlight performance optimizations such as cache for resources enumeration (#421).

**Example**

![image](https://user-images.githubusercontent.com/16480203/119524058-9303e600-bd7d-11eb-8c12-24783969ca23.png)

**Comment by sjourdan** [comment]
it works well! can you explicit the wording for the user, like "Scan took 9s" (I find "Done in" too vague for someone not aware of the intention here). Thanks!

**Comment by sjourdan** [comment]
or better @sundowndev your wording on the HTML output is better: "Scan Duration: 8s"

**Comment by sjourdan** [comment]
LGTM!

```
[...]
Found 13 resource(s)
 - 76% coverage
 - 10 covered by IaC
 - 1 not covered by IaC
 - 2 missing on cloud provider
 - 0/10 changed outside of IaC
Scan duration: 9s
```
