### ISSUE TITLE
False positive: aws_iam_role AssumeRolePolicy ordering

### ISSUE THREAD

**Issue by mwarkentin** [cloudskiff/driftctl#551]
**Description**
I'm getting a "changed resource" that seems to be a false positive (terraform plan shows no diff locally). You can see that the end result doesn't appear to be any change, but just swapping the order of the list items.

Could this be some change in how terraform plans since 0.12? I'm not sure if driftctl uses the terraform version we have defined or has its own logic for planning.

```
Found changed resources:
  - Wave__DevDynamoDBFromOmaha (aws_iam_role):
    ~ AssumeRolePolicy:
        {
          "Statement": [
            {
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Principal": {
                "AWS": [
                  ~ "arn:aws:iam::4472***:role/Wave__OmahaProdETLWorkloadsRole" => "arn:aws:iam::4472***:role/Wave__OmahaInstance",
                  ~ "arn:aws:iam::6958***:role/Wave__OmahaShadowDataLakeRole" => "arn:aws:iam::4472***:role/Wave__OmahaDevETLWorkloadsRole",
                  "arn:aws:iam::6958***:role/Wave__DataFromLegacy",
                  ~ "arn:aws:iam::4472***:role/Wave__OmahaDevETLWorkloadsRole" => "arn:aws:iam::6958***:role/Wave__OmahaShadowDataLakeRole",
                  ~ "arn:aws:iam::4472***:role/Wave__OmahaInstance" => "arn:aws:iam::4472***:role/Wave__OmahaProdETLWorkloadsRole"
                ]
              },
              "Sid": ""
            }
          ],
          "Version": "2012-10-17"
        }
```

**Environment**
 - OS: MacOS 11.3
 - driftctl version: 0.8
 - terraform version: 0.12.31

**How to reproduce**

**Possible Solution**

**Additional context**

**Comment by lotoussa** [comment]
#376 related

**Comment by mwarkentin** [comment]
@lotoussa thanks, missed that one when I checked - is it helpful to keep this open or should I close as a dupe?

**Comment by lotoussa** [comment]
> @lotoussa thanks, missed that one when I checked - is it helpful to keep this open or should I close as a dupe?

I think we can close the ticket since the other one is already handle on the board of the next release.
Thanks for your feedback!

**Comment by mwarkentin** [comment]
Closing as duplicate of #376
