### ISSUE TITLE
More information to track drift back to specific terraform states and resources

### ISSUE THREAD

**Issue by mwarkentin** [cloudskiff/driftctl#554]
**Description**
I'd like to be able to track drifts back to the terraform / state where they're defined? 

```
Scanned states (8)
Scanning resources ⣽ (2389)
Scanned resources (2986)

...

Found changed resources:
  - Wave__DevDynamoDBFromOmaha (aws_iam_role):

...

Found 225 resource(s)
 - 3% coverage
 - 7 covered by IaC
 - 218 not covered by IaC
 - 0 missing on cloud provider
 - 2/7 changed outside of IaC
```

I realized that seeing this doesn't give me any indication of where I should be looking for the drifted resource or which state it's in so I can do a terraform plan to verify the drift.

I could search for the resource name in our code (`Wave__DevDynamoDBFromOmaha`) however we often interpolate things like environment (`Dev`) so I wouldn't even be able to do a grep to find it.

**Example**

This could be a matter of expanding the resource type which is exposed:

```
Found changed resources:
  - Wave__DevDynamoDBFromOmaha (aws_iam_role):
```

Could become something like:

```
Found changed resources:
  - Wave__DevDynamoDBFromOmaha (module.dev_dynamodb_from_omaha_role.aws_iam_role.main in s3://terraform-state-bucket/accounts/foo.tfstate):
```

This would make it easy to see which terraform state (`s3://terraform-state-bucket/accounts/foo.tfstate`) the drift came from (we have dozens or possibly over 100 in some of our accounts that we would scan) as well as which terraform resource to look at (`module.dev_dynamodb_from_omaha_role`).

**Comment by wbeuil** [comment]
Hey @mwarkentin, thanks for your implication in driftctl 🙏🏻 . This is in fact a good idea to be able to know from which state the resource that drifted is from.

**Comment by eliecharra** [comment]
Created implementation issues with details here #873 #874 #875 #876

**Comment by sjourdan** [comment]
LGTM 

```sh
❯  LOG_LEVEL=error driftctl-0.15-pre scan --from tfstate://**/*.tfstate --deep
Scanned states (3) 
Found resources not covered by IaC:
  aws_s3_bucket:
    - driftctl-qa-s3-bucket-manual
Found changed resources:
  From tfstate://1/terraform.tfstate
    - driftctl-qa-s3-bucket-1 (aws_s3_bucket.one):
        + tags: <nil> => {
  yadda: "yadda"
}
  From tfstate://3/terraform.tfstate
    - driftctl-qa-s3-bucket-3 (aws_s3_bucket.three):
        + server_side_encryption_configuration: <nil> => [map[rule:[map[apply_server_side_encryption_by_default:[map[kms_master_key_id: sse_algorithm:AES256]]]]]]
Found 4 resource(s)
 - 75% coverage
 - 3 resource(s) managed by terraform
     - 2/3 resource(s) out of sync with Terraform state
 - 1 resource(s) not managed by Terraform
 - 0 resource(s) found in a Terraform state but missing on the cloud provider
Scan duration: 24s
```

**Comment by mwarkentin** [comment]
Exciting! 😁

**Comment by eliecharra** [comment]
This is weird :

> ```shell
>         + server_side_encryption_configuration: <nil> => [map[rule:[map[apply_server_side_encryption_by_default:[map[kms_master_key_id: sse_algorithm:AES256]]]]]]
> ```

We should investigate this.

**Comment by sundowndev** [comment]
> This is weird :
> 
> > ```shell
> >         + server_side_encryption_configuration: <nil> => [map[rule:[map[apply_server_side_encryption_by_default:[map[kms_master_key_id: sse_algorithm:AES256]]]]]]
> > ```
> 
> We should investigate this.

@sjourdan we expect to have a proper formatting for `driftctl-qa-s3-bucket-3.server_side_encryption_configuration`, can you provide a snippet to reproduce this bug in a new issue ? thanks

**Comment by sjourdan** [comment]
:arrow_up: good catch, seperate issue opened, keeping this one closed.
