### ISSUE TITLE
Create deep mode as experimental feature

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#572]
**Description**

With 0.10 released (full refacto), move deep mode to experimental, so as to support more resources quickly

Discussion: https://github.com/cloudskiff/driftctl/discussions/343

**Example**

- by default, quick mode (no attributes comparison, enumeration only). Consequence: resource configuration won't be compared in this mode. Much faster.
- using `--deep` triggers pre-0.10 behavior, experimentally (`DCTL_DEEP`).

**Comment by sundowndev** [comment]
> using --deep triggers pre-0.10 behavior, experimentally (DCTL_DEEP).

Do you mean disabling the current behavior by default ? I think the point of an experimental feature is to not change the default behavior so the usage of the experimental feature by the user is always intentional.

**Comment by eliecharra** [comment]
The fact is that the default actual behavior IS experimental 😛

**Comment by sundowndev** [comment]
> The fact is that the default actual behavior IS experimental stuck_out_tongue

Yes that's true tho, I just think it's confusing to use the term experimental if it does not differ in any way with other features we introduce

**Comment by sjourdan** [comment]
Action @cloudskiff/engineering: split this one meta-issue in technical tasks

**Comment by eliecharra** [comment]
Splitted in multiples issues
