### ISSUE TITLE
GH Discussions should be notified in #activity on Discord

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#584]
**Description**

As a human being in severe email bankruptcy 
I want to be notified of new GH Discussions on the #activity channel of the community Discord
So that I can know about important activity that I would otherwise probably miss

**Example**

**Comment by eliecharra** [comment]
@sjourdan I updated hooks to send theses two additional kind of event 

![image](https://user-images.githubusercontent.com/6154987/120769663-a3565680-c51d-11eb-8041-e479a45f7580.png)

Let's see if it works

**Comment by sjourdan** [comment]
Works perfectly well, thanks!! 

![image](https://user-images.githubusercontent.com/419121/120770441-6d65a200-c51e-11eb-9de3-c8fa651a386e.png)
