### ISSUE TITLE
ERRO[0009] unsupported attribute "enclave_options"

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#59]
**Description**
I got this error: `ERRO[0009] unsupported attribute "enclave_options"` 
This is related to a simple EC2 instance resource: 

```
# Create AWS EC2 Instance
resource "aws_instance" "main" {
  ami           = data.aws_ami.ubuntu.id
  instance_type = "t2.nano"

  tags = {
    Name  = var.name
    TTL   = var.ttl
    owner = "${var.name}-guide"
  }
}

```

This is new from 3.22.0 https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md#3220-december-18-2020

**Example**
I was following the hashicorp tutorial [here](https://learn.hashicorp.com/tutorials/terraform/secrets-vault).

See the tfstate attached

[terraform.zip](https://github.com/cloudskiff/driftctl/files/5764961/terraform.zip)

** Context ** 

https://docs.aws.amazon.com/enclaves/latest/user/nitro-enclave.html

_AWS Nitro Enclaves is an Amazon EC2 feature that allows you to create isolated execution environments, called enclaves, from Amazon EC2 instances. Enclaves are separate, hardened, and highly constrained virtual machines. They provide only secure local socket connectivity with their parent instance._

It's set to false by default

**Comment by eliecharra** [comment]
@sjourdan We only support aws provider version 3.19, should we plan an update to 3.22 in the next version ?

**Comment by sjourdan** [comment]
Good catch! Yes I think we should try to keep our tool as synchronized as possible. Let's add this to a future release 👍🏻

**Comment by eliecharra** [comment]
We could go further and ignore incompatible fields to allow us to handle state generated with a newer version.
We also should stop execution and do not display unmanaged resources when a resource cannot be read from state, this output inconsistent result to the user.

**Comment by eliecharra** [comment]
@sjourdan We fixed this one by ignoring fields not known in our current provider schema. Note that provider version was not upgraded.
