### ISSUE TITLE
False positive bucket_prefix on aws_s3_bucket

### ISSUE THREAD

**Issue by wbeuil** [cloudskiff/driftctl#614]
**Description**

Should not be seen as a drift since it's a Terraform internal attribute.

```
resource "aws_s3_bucket" "test-prefix" {
  bucket_prefix = "test-prefix-"
}
```

```
Found changed resources:
    - test-prefix-20210611092741609600000001 (aws_s3_bucket):
        - bucket_prefix: "test-prefix-" => <nil>
```

**Possible Solution**

Let's delete this attribute inside the `NormalizeFunc` of the `aws_s3_bucket` with the next architecture:

```
val.SafeDelete([]string{"bucket_prefix"})
```

**Comment by a-vorobiev** [comment]
Is that issue free for grabs?
I'd like to implement the change as my first contribution, look pretty straightforward.

**Comment by eliecharra** [comment]
@a-vorobiev Yeah you can go on !
