### ISSUE TITLE
get started with driftctl even with no tfstate

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#623]
**Description**

_As a user just getting started
I want to use driftctl features (like the driftignore generator or scan) 
So that I can start 100% from scratch_

- we currently assume users already have at least one tfstate and it may not be the case
- at least, nothing is preventing driftctl to display a full report by "simulating" an empty terraform state

**Example**

```
❯  driftctl scan -o json://stdout |  driftctl  gen-driftignore -i /dev/stdin > .driftignore
[...]
lstat terraform.tfstate: no such file or directory
unexpected end of JSON input
```

Reproduce with a simple empty repo: 

```hcl
terraform {
  required_version = "= 1.0.0"
  required_providers {
    aws    = "= 3.44.0"
    random = "= 3.0.0"
  }
}
```

Scan: 

```shell
driftctl scan -o json://stdout |  driftctl  gen-driftignore -i /dev/stdin > .driftignore
[...]
lstat terraform.tfstate: no such file or directory
unexpected end of JSON input
```

Now terraform apply the empty folder to generate an empty state: 

```shell
❯  cat terraform.tfstate 
{
  "version": 4,
  "terraform_version": "1.0.0",
  "serial": 1,
  "lineage": "b2e07f9f-f3ba-5abb-0840-3feef6dfebb9",
  "outputs": {},
  "resources": []
}
```

Now scan & gen-driftignore can work.

**Comment by AzySir** [comment]
Use case may also exist when templating an s3 bucket with a statefile. 

**S3 Bucket Naming Convention** - `<component>-tf-state`

**Component List**
* Networking
* Security
* Shared-Services
* Prod
* Non-Prod

**Description**

Not all the components above will share the same s3 bucket names. I.e Networking will have `vpc-tf-state` where as Prod/NonProd might have `application-tf-state` 

**Code to be run**

```

 for component in components:
   query +=  --from '{component} ' 
 
driftctl scan --from {query}
 
```

**Issue**
If the component does not exist in the account the driftctl fails. --skip-if-not-exist flag or something along those lines would be great. 

The above syntax in my opinion does not seem to be user friendly 

Part 2) Adding this Flag to an environment variables as this is always helpful and clean i.e pipeline(s)

**Comment by eliecharra** [comment]
I think this issue overlap https://github.com/cloudskiff/driftctl/issues/640 @sjourdan ?

**Comment by sjourdan** [comment]
> I think this issue overlaps #640 @sjourdan ?

yeah I think #640 is part of something bigger with #623 - probably some reorganization / split is needed.

**Comment by sjourdan** [comment]
referencing here the suggestion by @AzySir from another issue => https://github.com/cloudskiff/driftctl/issues/494#issuecomment-860829111

**Comment by eliecharra** [comment]
The original issue opened by @sjourdan is not really the same thing as @AzySir's comment. We opened a dedicated issue to handle @AzySir's case : #697
