### ISSUE TITLE
Missing new line in .driftignore makes appending stdout unignore the last entry

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#633]
**Description**

a) user have a preexisting working .driftignore 
b) user updates the .driftignore by appending new content to it
c) fail (previous last line is now un-ignored because of formatting)

```
aws_sqs_queue.https://sqs\.us-east-1\.amazonaws\.com/141177182257/queue-6qaidu\.fifo# Resources not covered by IaC
aws_kms_alias.alias/yaddakey

```

**Environment**
 - OS: F34
 - driftctl version: 0.10.0-pre
 

**How to reproduce**

1. start with a working .driftignore file
2. append a new drift to it:

```shell
❯  DCTL_TF_PROVIDER_VERSION=3.44.0 driftctl-0.10.0 scan -o json://stdout |  DCTL_TF_PROVIDER_VERSION=3.44.0 driftctl-0.10.0  gen-driftignore -i /dev/stdin >> .driftignore
```

=> confirm `# Resources not covered by IaC` is at the end of the last line, not a new one 

**Possible Solution**

**Additional context**

**Comment by sundowndev** [comment]
The main issue behind this is that we don't put a newline at the end of the output, so any appended content will need to append a newline before. I wonder if we should just add a newline at the end so if the user use `gen-driftignore` multiple times, it works as expected. But obviously we can't anticipate the file content as we only send output to stdout.

**Comment by eliecharra** [comment]
> I wonder if we should just add a newline at the end

Sound like the right approach for me, it is a good practice to have trailing newline in theses kind of files even if only for terminal output when running `cat .drifignore`. This is a quick fix maybe we can let someone of the community handle it

**Comment by a-vorobiev** [comment]
May I take this one?

**Comment by wbeuil** [comment]
Of course you can !

**Comment by a-vorobiev** [comment]
> Of course you can !

I can't assign it to myself, can somebody do that for me please?

**Comment by sjourdan** [comment]
LGTM, after running 3 times the same command, I got 3 new lines!

```
❯  cat .driftignore
# Resources not covered by IaC
google_storage_bucket.864694843864683
google_storage_bucket.driftctl-qa-bucket-manual-1
google_storage_bucket.manual_bucket_in_europe
# Missing resources
google_storage_bucket.driftctl-b13bskw4rxwiqgy1
google_storage_bucket.driftctl-b13bskw4rxwiqgyz




```
