### ISSUE TITLE
`tags_all` attribute will produce drifts

### ISSUE THREAD

**Issue by wbeuil** [cloudskiff/driftctl#635]
**Description**
Since terraform provider 3.38.0, we can enable provider-level tagging as an alternative to tagging each resources with the same tags. It produces drifts on driftctl analysis.

**How to reproduce**
```
provider "aws" {
  default_tags {
    tags = {
      Environment = "Test"
    }
  }
}

resource "aws_instance" "test" {
  ami           = "ami-0b2ca94b5b49e0132"
  instance_type = "t2.micro"
  root_block_device {
    tags = {
      "Name"      = "test"
    }
  }
}

resource "aws_s3_bucket" "test" {
  bucket_prefix = "test-bucket-"
}
```

```
Found changed resources:
    - i-08121f2f13a5cbe30 (aws_instance):
        + tags: <nil> => {
  Environment: "Test"
}
    - test-bucket-20210611121140651700000001 (aws_s3_bucket):
        + tags: <nil> => {
  Environment: "Test"
}
```

**Possible Solution**
We can create a middleware to add global tags to each resources' tags and then delete the `tags_all` attribute to avoid duplicate.

**Comment by sjourdan** [comment]
I have this issue without enabling anything

```
Found changed resources:
    - vol-0e022e1567c9cec58 (aws_ebs_volume):
        + tags_all: <nil> => {
  Terraform: "true",
  Name: "aws-www-1-root"
} (computed)

```

My provider config: 

```
terraform {
  required_version = "= 1.0.0"
  required_providers {
    aws = "= 3.46.0"
  }
  backend "s3" {
  [...]
}

provider "aws" {
  region = var.aws_region
}

```

**Comment by sjourdan** [comment]
report of what was debated on discord: 

- it will generate way too much noise to users if we keep those `tags_all` attributes
- future deep mode will lower the impact of this change
- step 1: ignore tags_all for now (_A mvp could be to add a middleware that remove theses fields in every resource (should be run after all middlewares)_ says @eliecharra) 
- step 2: make a better middleware (in sync with deep mode roadmap)

**Comment by sjourdan** [comment]
won't fix: `tags_all` will stay ignored for now.
