### ISSUE TITLE
aws_sqs_queue false positive (NamePrefix: "" => <nil>)

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#636]
**Description**

Running the default provider in 0.10 (3.19), got this false positive:

```shell
Found changed resources:
  - https://sqs.us-east-1.amazonaws.com/141177182257/queue-driftctl-qa-20210614.fifo (aws_sqs_queue):
    ~ NamePrefix: "" => <nil>
```

Note: it's working perfectly well when using the correct version of the provider.

**Environment**
 - OS: fedora 34
 - driftctl version:0.10.0-pre
 - terraform 1.0.0
 - aws provider 3.44 generated the state, 3.19 read it

**How to reproduce**

- apply this: 
 
```hcl
resource "aws_sqs_queue" "fifo_queue" {
  name                        = "queue-driftctl-qa-20210614.fifo"
  fifo_queue                  = true
  content_based_deduplication = true
}
```

- then `driftctl scan`

**Possible Solution**

**Additional context**

This is a provider mismatch (with 0.10 default). No big deal.

**Comment by eliecharra** [comment]
Closing since this is a provider version mismatch
