### ISSUE TITLE
aws_cloudfront_distribution: attributes "active_trusted_signers" and "cache_behavior" are required

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#639]
**Description**

When scanning with 2.70 an `aws_cloudfront_distribution` generated with 3.44

```
❯  DCTL_TF_PROVIDER_VERSION=2.70.0 driftctl-0.10.0 scan
Scanned states (1) 
attributes "active_trusted_signers" and "cache_behavior" are required
```

**Environment**
 - OS: fedora34
 - driftctl version: 0.10.0-pre

**How to reproduce**

**Possible Solution**

**Additional context**

issue opened for use KB as this is very edge-case, who would scan with 2.70 a state generated with 3.44

**Comment by eliecharra** [comment]
Closing since it is a terraform provider mismatch
