### ISSUE TITLE
aws_default_security_group: "attribute "timeouts" is required"

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#642]
**Description**

This is a mismatch when scanning with AWS Provider 2.70 and using a TFState from 3.44.0 - on the `aws_default_security_group` special resource

```shell
❯  DCTL_TF_PROVIDER_VERSION=2.70.0 driftctl-0.10.0 scan
Scanned states (1) 
attribute "timeouts" is required
```

**Environment**
 - OS:
 - driftctl version:

**How to reproduce**

```hcl
# add a vpc
resource "aws_vpc" "a" {
  cidr_block       = "10.0.0.0/16"

  tags = {
    Name = "QA VPC"
  }
}

resource "aws_default_security_group" "default" {
  vpc_id = aws_vpc.a.id

  ingress {
    protocol  = -1
    self      = true
    from_port = 0
    to_port   = 0
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
``` 

- apply the above hcl
- scan: `DCTL_TF_PROVIDER_VERSION=2.70.0 driftctl-0.10.0 scan`

**Possible Solution**

**Additional context**

Issue for KB only. Makes no sense to scan a v3 state with a v2 provider.

**Comment by eliecharra** [comment]
Closing since it is a terraform provider version mismatch
