### ISSUE TITLE
Run unit test on windows

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#653]
**Description**
Some bugs are not covered as they are os-specific. Like https://github.com/cloudskiff/driftctl/pull/651 
We should setup a windows run in CircleCI to detect theses cases in the future. Maybe we can use CircleCI windows executor https://circleci.com/docs/2.0/executor-types/#using-the-windows-executor

**Comment by OrenLeung** [comment]
UpVote! 🚀
