### ISSUE TITLE
Empty string JSON key

### ISSUE THREAD

**Issue by OrenLeung** [cloudskiff/driftctl#655]
**Description**
- null key in the JSON output with `"message": "You have unmanaged security group rules that could be false positives, find out more at https://docs.driftctl.com/limitations"`

**Environment**
 - OS: Windows 10
 - driftctl version: v0.9.1
 - terraform version: v0.15.4
 - terraform providers versions: aws@3.4.2
**How to reproduce**
```
driftctlbeta scan --from tfstate+s3://BUCKET/TERRAFORM.TFSTATE --output json://driftctl.json
$driftObject = Get-Content "driftctl.json"  | ConvertFrom-Json
```
Error:
```
ConvertFrom-Json : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
```

This is caused as powershell `ConvertFrom-JSON`  (v5.1.1) can not parse null keys. https://stackoverflow.com/questions/62191676/convertfrom-json-returns-cannot-process-argument-because-the-value-of-argument

specifically, there is a null key in `driftctl.json` for 
```
"alerts": {
		"": [
			{
				"message": "You have unmanaged security group rules that could be false positives, find out more at https://docs.driftctl.com/limitations"
			}
		],
```

**Possible Solution**
- not make the key empty string like by having "unmanaged_false_positives" or something more descriptive than ""

**Additional context**
Even though, this is a problem specifically with `ConvertFrom-JSON`, the root cause lies with an non-descriptive key `""`

**Comment by OrenLeung** [comment]
it should be easy fix one line. I couldn't find yall are outputing the "alerts" key in the json, but i was able to find this.

https://github.com/cloudskiff/driftctl/blob/7bcbe0bf93f5ba72a2cc5b05820187d373dbfa88/pkg/analyser/analyzer.go#L18

**Comment by eliecharra** [comment]
@OrenLeung I need to check why we have empty keys there, if it's an issue on our side I will fix it but if it is a normal behavior this issue will be a wontfix since it is a bug in Powershell.

**Comment by eliecharra** [comment]
Ok I can confirm that the empty string is a normal behavior and may append, so I'm closing this one as we output a valid JSON.
