### ISSUE TITLE
Check for config dir existence first

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#669]
**Description**

As a user, I would expect driftctl to check for the config-dir availability and writability before going further and download a provider. 

```
❯  driftctl scan --config-dir /yadda
[...]
DEBU[0000] New provider library created
DEBU[0000] provider not found, downloading ... path=/yadda/.driftctl/plugins/linux_amd64/terraform-provider-aws_v3.44.0
Downloading terraform provider: aws
DEBU[0000] Downloading provider path=/yadda/.driftctl/plugins/linux_amd64 url=https://releases.hashicorp.com/terraform-provider-aws/3.44.0/terraform-provider-aws_3.44.0_linux_amd64.zip
DEBU[0005] Decompressing archive dst=/yadda/.driftctl/plugins/linux_amd64 src=/tmp/terraform-provider274317203
mkdir /yadda: permission denied
❯  echo $?
1
``` 

**Environment**
 - OS: fedora 34
 - driftctl version: 0.10.0-pre
 - terraform version: 1.0.0
 - terraform providers versions: aws@3.44.0

**How to reproduce**

See above (`--config-dir /yadda` is enough)

**Possible Solution**

1. dir exists? 
2. dir is writable? 

**Additional context**

**Comment by lotoussa** [comment]
nevermind
