### ISSUE TITLE
driftctl should check if the driftignore is valid

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#670]
**Description**

If I pass something like `/dev/random` to the `--driftignore` option, nothing good happens.
We should somehow find out that at least the file is a file, and is ASCII and structured as expected

```
❯  file /dev/random 
/dev/random: character special (1/8)
❯  file .driftignore2000 
.driftignore2000: ASCII text
```

**Environment**
 - OS: fedora 34
 - driftctl version: 0.10.0-pre
 - terraform version: 1.0.0
 - terraform providers versions: aws@3.44.0, 

**How to reproduce**

```
$ driftctl scan --driftignore="/dev/random"
```

- enjoy (and kill the driftctl process using another terminal)

**Possible Solution**

**Additional context**

**Comment by eliecharra** [comment]
Closing since /dev/urandom never ends and it's not a common usecase
