### ISSUE TITLE
Changed resource aws_lambda_function noise (hash & size reported)

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#673]
**Description**

Driftctl compares state values that are probably lifecycle-ignored by Terraform because of some external deployment workflow.

```
Found changed resources:
    - driftctl-REDACTED (aws_lambda_function):
        ~ source_code_hash: "F2eSYEGZHd4kNMMmKQJiKf9GuZexQat1ebpexMEgf6Y=" => "x9zUwqPvHtmavLj/+oPfQL1KFY9sWNyqQlGV35+J2Ow=" (computed)
        ~ source_code_size: 8.046928e+06 => 8.048512e+06 (computed)
```

**Environment**
 - OS: f34
 - driftctl version: 0.10.0-pre
 - terraform version: 1.0.0
 - terraform providers versions: 

**How to reproduce**

- create a lambda with tf
- run driftctl: no change
- modify the lambda
- run driftctl: confirm changed resources

**Possible Solution**

- proposal 1: let's remove completely both alerts because we think 99% of users use `lifecycle_ignore` in Terraform for lambdas
- proposal 2: remove `source_code_size` from driftctl as it's a necessary duplicate of `source_code_hash`. Let the user decide to ignore this one or not using the driftignore

**Additional context**

**Comment by sjourdan** [comment]
This is a real drift, let's talk about how to improve the behavior for users in 0.11

**Comment by sundowndev** [comment]
I'd usually say to follow proposal 2, remove `source_code_size` from dctl and let the user ignore `source_code_hash` or not. Because some users may want to get notified when the source code of their lambda change unexpectedly. But the lambda source code isn't part of IaC, is it? It's not the job of driftctl to report such issues.

**Comment by sjourdan** [comment]
then let's do exactly this @sundowndev

**Comment by sjourdan** [comment]
from (0.11): 

```
Found changed resources:
    - qa-driftctl-20210614-lambda-demo (aws_lambda_function):
        ~ qualified_arn: "arn:aws:lambda:us-east-1:141177182257:function:qa-driftctl-20210614-lambda-demo:$LATEST" => "arn:aws:lambda:us-east-1:141177182257:function:qa-driftctl-20210614-lambda-demo:1" (computed)
        ~ source_code_hash: "JDgcsP0ZYQ2ViAwhuM8BVkHTFCULxEbxg94/n7odKsg=" => "1u6zYUoKtQ+OmrVmauV1TqZozjJzEOWyG38EoY12Eag=" (computed)
        ~ source_code_size: 205 => 3.8992805e+07 (computed)
        ~ version: "$LATEST" => "1" (computed)
```

to: 0.12-pre 

```
Found changed resources:
    - qa-driftctl-20210614-lambda-demo (aws_lambda_function):
        ~ qualified_arn: "arn:aws:lambda:us-east-1:141177182257:function:qa-driftctl-20210614-lambda-demo:$LATEST" => "arn:aws:lambda:us-east-1:141177182257:function:qa-driftctl-20210614-lambda-demo:1" (computed)
        ~ source_code_hash: "JDgcsP0ZYQ2ViAwhuM8BVkHTFCULxEbxg94/n7odKsg=" => "1u6zYUoKtQ+OmrVmauV1TqZozjJzEOWyG38EoY12Eag=" (computed)
        ~ version: "$LATEST" => "1" (computed)
```

LGTM!
