### ISSUE TITLE
SNS Topics, Policies and Subscriptions from other regions showing up in scan

### ISSUE THREAD

**Issue by datfinesoul** [cloudskiff/driftctl#685]
**Description**

I was doing a scan on `us-east-2` for drift, and saw SNS resources from `ap-northeast-1` pop up in the scan.  These SNS resources are related to an organization wide CloudTrail setup.
```
  aws_sns_topic:
    - arn:aws:sns:ap-northeast-1:566134080430:cloudtrail-organization-wide-log-delivery
        Name: cloudtrail-organization-wide-log-delivery
  aws_sns_topic_policy:
    - arn:aws:sns:ap-northeast-1:566134080430:cloudtrail-organization-wide-log-delivery
  aws_sns_topic_subscription:
    - arn:aws:sns:ap-northeast-1:566134080430:cloudtrail-organization-wide-log-delivery:82bcdcbc-dc78-43d6-95f0-eeb46be7c422
```

**Environment**
 - OS: Ubuntu 18.04
 - driftctl version: 0.10.0
 - terraform version: 1.0.0
 - terraform providers versions: aws@3.19.0

**How to reproduce**
- Create SNS Topic in `ap-northeast-1`
- Scan for drift in `us-east-2`

**Possible Solution**
- The resource should only show up, if i'm scanning `ap-northeast-1`

**Additional context**
I'm new to driftctl, so please let me know if there is a good way to get logs or other helpful debugging information.  I'll gladly add additional information to the ticket.

**Comment by eliecharra** [comment]
Hi @datfinesoul thanks for your interest in driftctl 🙏🏻 

This is a really stange behavior, are you sure you are using proper credentials on correct `us-east-2` region while launching driftctl ?

Can you check with `LOG_LEVEL=debug` env var ? You should see something like this

![image](https://user-images.githubusercontent.com/6154987/123073220-845d2d00-d416-11eb-9a2b-6dd08ab7d5e7.png)

**Comment by datfinesoul** [comment]
Here is the output I have for this run:
```text
DEBU[0014] Closing providers
DEBU[0014] Closing provider key=aws
DEBU[0014] Closing gRPC client alias=ap-northeast-1
DEBU[0000] New provider library created
DEBU[0000] Found existing provider path=/home/phadviger/.driftctl/plugins/linux_amd64/terraform-provider-aws_v3.19.0_x5
DEBU[0000] Starting gRPC client alias=us-east-2
DEBU[0002] New gRPC client started alias=us-east-2
DEBU[0002] Terraform provider initialized alias=us-east-2 name=aws
```
One thing about how I run driftctl currently, is that this runs in a script through all the different regions I manage, so this runs after the initial run through the main `ap-northeast-1` region of the account.  Let me know if that helps.

I'll include a snippet from the script:

```bash
AWS_REGION="ap-northeast-1"
driftctl scan ${WORKSPACES[@]} \
    --tfc-token "$(<"${HOME}/.terraform.d/credentials.tfrc.json" jq -r '.credentials."app.terraform.io".token')"
AWS_REGION="us-east-2"
driftctl scan ${WORKSPACES[@]} \
    --tfc-token "$(<"${HOME}/.terraform.d/credentials.tfrc.json" jq -r '.credentials."app.terraform.io".token')"
```

**Comment by eliecharra** [comment]
> and saw SNS resources from ap-northeast-1 pop up in the scan.

Are these resources appears in the missing section ?

Are you using a single state with resources from multiples regions within (by using provider aliases) ? Actually driftctl does not support this and show every resources from other region than the one used for the scan as missing.

**Comment by datfinesoul** [comment]
> Are these resources appears in the missing section ?

Yes, the resources are showing up in the missing section.

> Are you using a single state with resources from multiples regions within (by using provider aliases) ? Actually driftctl does not support this and show every resources from other region than the one used for the scan as missing.

- The `${WORKSPACES[@]}` section in the snippet above expands into 4 `tfstate+tfcloud://` state files.  Each state file is tied to a single region each.
- None of the code is using provider aliases.

**Comment by eliecharra** [comment]
Ok, so you have to scan each state separately instead of scanning 4 states at once, it will fix your issues if you have one region per state. Be carefull to pass proper AWS_REGION env var to driftctl according to the state you are scanning.

**Comment by datfinesoul** [comment]
Per discussion on discord, I'm trying out 2 potential solutions

1) the first one is to scan all states at once (what you did in the issue you opened) multiples times, and provide each time a driftignore to exclude resources from other region than the current one. For example you run driftctl one on us-east-1, you have to provide ignore file to exclude all resources contained in other regions. This approach is a lot of pain and this is probably not what you want :sweat_smile: 

2) Iterate over your state and scan only one state at once, with proper region passed to driftctl. For example use `AWS_REGION=us-east-1 driftctl scan --from tfstate+tfcloud://your-state-with-us-east-1-resources.tfstate` then do the same for each state

I'll post updates after I work with these possible solutions for a bit.

**Comment by eliecharra** [comment]
I'm closing this one, don't hesitate to contact us on discord for further help
