### ISSUE TITLE
Clarify HTML report input wording

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#693]
**Description**

As a HTML output user,
I want the search bar to search resource IDs and resource types
So I can quickly filter services ("s3") 

(ux wise, the dropdown list on the right can be misleading as you may think that typing "s3" relates to Resource Types, while in fact it's only filtering resource IDs) 

**Example**

![image](https://user-images.githubusercontent.com/419121/123066783-a9e73800-d410-11eb-92f2-b212ff052370.png)

**Comment by sundowndev** [comment]
I think the issue comes from the placeholder of the input. May be a clearer text would be more understandable to the user ?

Example : 

![image](https://user-images.githubusercontent.com/16480203/123272371-fa8a8e00-d501-11eb-83c4-5a8ab92ecbe2.png)

**Comment by eliecharra** [comment]
I think we should fix the wording in a first place. I think this is not trivial to do a proper fuzzy filtering

**Comment by eliecharra** [comment]
Ok so let's go with @sundowndev proposal

**Comment by sjourdan** [comment]
lgtm!
