### ISSUE TITLE
Cannot specify tfstate file using glob pattern

### ISSUE THREAD

**Issue by Tocyuki** [cloudskiff/driftctl#695]
**Description**

I cannot specify tfstate file using glob pattern.
However, the manual states that it can be used.
https://docs.driftctl.com/0.10.0/installation

```
# Using glob pattern
$ driftctl scan --from tfstate://path/to/**/*.tfstate
$ driftctl scan --from tfstate+s3://path/to/**/*.tfstate
```

**Environment**
There is no problem before driftctl v0.10.0.

 - OS: MacOS11.2.3 & docker comopse v1.29.0
 - driftctl version: v0.11.0
 - terraform version: v1.0.0
 - terraform providers versions: aws@3.44.0

**How to reproduce**

docker-compose.yml

```docker
version: '3.8'
services:
  driftctl:
    image: cloudskiff/driftctl:v0.11.0
    volumes:
      - ./terraform:/terraform
    working_dir: /terraform
```

command

```
docker-compose run --rm driftctl scan --from tfstate+s3://example-tfstate-bucket/*.tfstate
```

result

```
Scanned states (0) 
no Terraform state was found in example-tfstate-bucket/*.tfstate, exiting
```

Only one tfstate file is displayed in the specified S3 bucket.

**Possible Solution**

It can be executed by specifying the name of the tfstate file.

```
docker-compose run --rm driftctl scan --from tfstate+s3://example-tfstate-bucket/example.tfstate
```

**Additional context**

The same situation with Docker and commands.

**Comment by eliecharra** [comment]
@Tocyuki Thanks a lot for this report, we fixed issues on S3 state enumeration on the lastest v0.11.1 can you confirm that it fixes your issues ?

**Comment by Tocyuki** [comment]
I confirmed that this issue has been fixed.
Thank you for fixing it.
