### ISSUE TITLE
driftctl 0.11.1 test failed on apple arm64

### ISSUE THREAD

**Issue by chenrui333** [cloudskiff/driftctl#700]
**Description**

**Environment**
 - OS: macOS 11-arm64
 - driftctl version: 0.11
 - terraform version: 1.0.0
 - terraform providers versions: 

**How to reproduce**
- install driftctl on apple m1
- run `driftctl --no-version-check scan`

**Possible Solution**
maybe it is the provider support issue on apple m1? not quite sure why it failed the regression test.

**Additional context**

---

relates to Homebrew/homebrew-core#79915

**Comment by wbeuil** [comment]
Hello @chenrui333, can you try running driftctl with a AWS Terraform Provider >= 3.30.0 as explained in this [comment](https://github.com/hashicorp/terraform-provider-aws/issues/16948#issuecomment-786395896). As of now when you use the command `driftctl scan` it will use by default the version 3.19.0 of the provider.

```bash
$ driftctl scan --tf-provider-version 3.30.0
```

**Comment by sjourdan** [comment]
We have a couple of M1 laptops here, we'll test this soon too

**Comment by sjourdan** [comment]
@GeraldCrescione I think you have a M1 laptop. You're now the happy owner of this issue with @wbeuil :)

**Comment by wbeuil** [comment]
@chenrui333, we released yesterday a new version of driftctl, `v0.12.0`.

Homebrew-core this time didn't fail on its [pipeline](https://github.com/Homebrew/homebrew-core/pull/80741/checks?check_run_id=3010945127). To be sure that we support apple M1, I tested driftctl on a new MacBook M1 setup with @GeraldCrescione and everything went smooth.

I'm gonna close this issue.
