### ISSUE TITLE
Feature Request: Support `default_tags` at terraform-provider-aws

### ISSUE THREAD

**Issue by kanata2** [cloudskiff/driftctl#706]
### Description
Currently, you can use `default_tags` for the purpose of adding tags to all resources,
but `driftctl` will detect these changes as a diff.

### Versions
- driftctl: v0.11.0
- Terraform: v1.0.0
- registry.terraform.io/hashicorp/aws: 3.45.0

### Example
```hcl
provider "aws" {
  default_tags {
    tags = {
      Environment = local.env
      Project     = local.project
    }
  }
}

resource "aws_s3_bucket" "test" {
  bucket = "test"
}
```

```sh
$ driftctl scan
...
Found changed resources:
    ...
    - test (aws_s3_bucket):
        + tags.Environment: <nil> => "dev"
        + tags.Project: <nil> => "project-a"
```

### Links
- https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider

**Comment by wbeuil** [comment]
Hello @kanata2, if you use the default `driftctl scan`, bear in mind that the default Terraform AWS provider used in driftctl will be the 3.19.0 version which has not the `default_tags` feature enabled. For this feature to work, you need to use at least the 3.38.0 version as told in this [blog post](https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider).

```
$ driftctl scan --tf-provider-version 3.38.0
```

**Comment by kanata2** [comment]
Hi, @wbeuil. Thanks for your feedback.
I overlooked `--tf-provider-version` option...
I think this will help me achieve what I want to do.
Thank you!
