### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Gary-Armstrong** [cloudskiff/driftctl#73]
**Description**
Panic due to invalid memory address while using docker image. I'm not a Go programmer but let me know how I can help.

**Environment**
 - OS: Docker 3.0.3 on macos 11.1
 - driftctl version: Container cloudskiff/driftctl 9156f3facc17   3 weeks ago

**How to reproduce**
From existing TF dir:
```
docker run \
  -v ~/.aws:/app/.aws:ro \
  -v $(pwd)/terraform.tfstate:/app/terraform.tfstate:ro \
  -v ~/.driftctl:/app/.driftctl \
  -e AWS_PROFILE=$AWS_PROFILE \
  cloudskiff/driftctl scan
Downloading AWS terraform provider: terraform-provider-aws_v3.19.0_x5
Scanning AWS on region: us-east-1
ERRO[0015] Unable to scan resources: A runner routine paniced: runtime error: invalid memory address or nil pointer dereference
Usage: driftctl scan [flags]

FLAGS:
      --filter string   JMESPath expression to filter on
                        Examples :
                          - Type == 'aws_s3_bucket' (will filter only s3 buckets)
                          - Type =='aws_s3_bucket && Id != 'my_bucket' (excludes s3 bucket 'my_bucket')
                          - Attr.Tags.Terraform == 'true' (include only resources that have Tag Terraform equal to 'true')

  -f, --from string     IaC source, by default try to find local terraform.tfstate file
                        Accepted schemes are: tfstate://,tfstate+s3://
                         (default "tfstate://terraform.tfstate")
  -o, --output string   Output format, by default it will write to the console
                        Accepted formats are: console://,json://PATH/TO/FILE.json
                         (default "console://")
  -t, --to string       Cloud provider source
                        Accepted values are: aws+tf
                         (default "aws+tf")

INHERITED FLAGS:
  -h, --help               Display help for command
      --no-version-check   Disable the version check

unable to run driftcl
```

**Possible Solution**
???

**Additional context**
Terraform v0.14.3 in local dir, Terraform state format version 4
There is a typo in the final error message: driftcl should be driftctl

**Comment by sjourdan** [comment]
Hey Gary, we have a build coming with an optionally enabled bug reporting feature, so we're coming back to you in a few hours, so your (buggy) use case will help many other users. 
Thank you!

**Comment by eliecharra** [comment]
@Gary-Armstrong Thanks for your feedback, this is very valuable for us 😃 Some other user reported us same kind of panic.

We just released v0.2.0, could you update your version and run it with `--error-reporting` flag ? 
It will will send us crash data for analysis.

Thank you for your interest in driftctl !

**Comment by Gary-Armstrong** [comment]
Just FYI, I ran it using latest image but get `Invalid AWS Region:` and am looking around for the best way to fix this. My `~/.aws/credentials` is fine, been using it all day. Will open another issue if needed.

**Comment by sjourdan** [comment]
does it help if you force the region using the environment variable `-e AWS_REGION=us-east-1` ?
that's what I use most of the time as I'm often switching between regions.

**Comment by Gary-Armstrong** [comment]
I think we can close this issue, especially after the chat session fixed my credentials issue, but if you want more data just let me know.

**Comment by sjourdan** [comment]
we'll close this one once we found the exact issue you ran into with the crash! thanks again for your time.

**Comment by tdeknecht** [comment]
I'm seeing a similar error: `ERRO[0001] Unable to scan resources: A runner routine paniced: runtime error: invalid memory address or nil pointer dereference`

With `--error-reporting` enabled I see the following messages. I've redacted the actual names in place of `<placeHolders>`. These resources already exist in the account, along with many others.

```
WARN[0001] Error reading iam policy arn:aws:iam::<accountID:policy/<policyName>[aws_iam_policy]: rpc error: code = Canceled desc = context canceled
WARN[0001] Error reading iam role <roleName>[aws_iam_role]: rpc error: code = Canceled desc = context canceled
WARN[0001] Error reading iam user <userName>[aws_iam_user]: rpc error: code = Canceled desc = context canceled
WARN[0001] Error reading <hostedZoneName>[aws_route53_zone]: rpc error: code = Canceled desc = context canceled
WARN[0001] Error reading key pair <keyPairName>: rpc error: code = Canceled desc = context canceled
WARN[0001] Error reading function <functionName>[aws_lambda_function]: rpc error: code = Canceled desc = context canceled
ERRO[0001] rpc error: code = Canceled desc = context canceled
```

There are many duplicates where duplicates exist (multiple Lambdas, roles, etc.). I also noticed the errors are sporadic. Sometimes I get zero output from error-reporting, other times I get about 10 messages, sometimes 5. Each appear to be different, but all related to the resources already existing.

I've created a dedicated IAM User for driftctl with the recommended permissions with a corresponding [profile driftctl] in `.aws/credentials`. I've also tested using an admin role with blanket permissions. Same results. My regular CLI commands work for both profiles.

I've tested this on Ubuntu 20.04 LTS (WSL2) and Win10 with the same results.

I've tested using TF version 12.30 (pre-provider lock file) and TF version 14.4.

**Comment by tdeknecht** [comment]
Confirmed MR #81 fixed the issue. Up and running!

**Comment by sjourdan** [comment]
hey @Gary-Armstrong, we may have fixed the issue in the 0.2.3 release, if you want to try again!

**Comment by Gary-Armstrong** [comment]
Running for 12 minutes so far with no panic.

**Comment by Gary-Armstrong** [comment]
After 17 minutes it completed reading AWS, and then it says
```
Unable to scan resources: Failed to read state file: The state file could not be read: read terraform.tfstate: is a directory
```
which is news to me :)
Maybe do this check at the start?

I rmdir terraform.tfstate and try again.

**Comment by sjourdan** [comment]
good catch and suggestion @Gary-Armstrong, thank you! I opened #86 to keep track of this one.

**Comment by Gary-Armstrong** [comment]
Thanks @sjourdan and after I rmdir terraform.tfstate and again run the docker command, I find there is another dir named terraform.tfstate which is apparently created by the container. I will open another issue for this.
