### ISSUE TITLE
Inline Security Group Rules should trigger alert to user

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#8]
**Description**
Using an `aws_security_group` resource, I declare rules using the `egress {}` and `ingress {}` blocks. 
The resulting rules are detected as "unmanaged" by `driftctl`, which is not true

**Environment**
 - OS: linux
 - driftctl version: v0.1.0

**How to reproduce**
[to_reproduce.tar.gz](https://github.com/cloudskiff/driftctl/files/5679194/to_reproduce.3.tar.gz)

- apply the above TF
- run driftctl scan
- confirm rules are detected as unmanaged

**Possible Solution**

**Additional context**
```
 $    AWS_REGION="eu-west-3" AWS_PROFILE="cloudskiff-demo" driftctl scan
Scanning AWS on region: eu-west-3
Found unmanaged resources:
[...]
  aws_security_group_rule:
    - sgrule-3926891421 (Type: egress, SecurityGroup: sg-00cc7a64235d09359, Protocol: All, Ports: All, Destination: 0.0.0.0/0)
    - sgrule-3913664463 (Type: ingress, SecurityGroup: sg-00cc7a64235d09359, Protocol: tcp, Ports: 443, Source: 0.0.0.0/0)
[...]

**Comment by eliecharra** [comment]
It is what we expect by design. Indeed for 2 distincts security groups, both managed by terraform with the same rules, however one done by inlining egress and ingress blocks (managed rules) and the other one done in the aws console (unmanaged rules), Terraform "re-writes" the tfstates so that it's impossible to know for sure if those blocks are managed or not.

Let's leave it open for now.

**Comment by sjourdan** [comment]
LGTM

![image](https://user-images.githubusercontent.com/419121/108392156-b82f0880-7212-11eb-8cd3-9d37f4fb3e92.png)
