### ISSUE TITLE
Acceptance test may hide permission issues

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#83]
**Description**
Acceptance test should be run with minimal permissions to cover potential missing permissions in documentation or other permissions issues. 

Since we run a terraform apply to generate required resource on remote side during Acc test execution, we cannot use a minimal read only permission set.

An approach could be to introduce `ACC_AWS_PROFILE` overriding default `AWS_PROFILE` to be used during terraform write operations during acc tests.

**Example**
ACC_AWS_PROFILE=read-write-profile AWS_PROFILE=read-only-profile DRIFTCTL_ACC=true make acc

**Comment by wbeuil** [comment]
Once the issue #103 is ready, we could before each test create the specific least-privileged role and use it to run the acceptance tests, what do you think @eliecharra ? We would add just one read-write (or just write) role to create needed resources but it would be easier to run tests.

Could simplify the test to `ACC_AWS_PROFILE=read-write-profile DRIFTCTL_ACC=true make acc`.

**Comment by eliecharra** [comment]
I think we should put less magic as possible in Acc tests.
It could lead to race condition if we want to run some tests in parallel, imagine two test starting at once, and two policy creation at the same time.

We also need to introduce automatic ignore of created policies in driftctl scans, so keeping references of created policies IDs etc ... 
It's adding a lot of complexity for a simple problem.
