### ISSUE TITLE
Multiple output files out of same scan operation

### ISSUE THREAD

**Issue by suchakraborty** [cloudskiff/driftctl#831]
Would it be possible to have 2 outputs for the same scan? like driftctl scan...-o json://... -o html://...

This would be helpful for me, as we have multiple environments, multiple regions, and would like to have regions specific html reports as well as json to easily create consolidated reports.

Another way probably more complicated would be to take multiple regions (and aws profiles) to create the consolidated report too - say working in terragrunt style foldering? But I can see that is way more complicated than just streaing the output through multiple channels to create different output files.

**Comment by sjourdan** [comment]
LGTM!

I could generate at once, with multiple drifts and unmanaged stuff and folders and outputs 

- a console output for humans
- an HTML report to be stored on S3 somewhere
- a json file for a script to process it and send it to Slack

sounds really good

```
❯  LOG_LEVEL=error CLOUDSDK_CORE_PROJECT=driftctl-sj-tests GOOGLE_APPLICATION_CREDENTIALS=keys/driftctl.json driftctl-0.15-pre scan --from tfstate://**/*.tfstate --to gcp+tf --tf-provider-version 3.82.0 --output console:// --output html://report.html --output json://report.json
```
