### ISSUE TITLE
Minimal enrichment for `aws_default_security_group_rule` middleware 

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#846]
We need almost of the field for `aws_security_group_rule`, check the middleware for an exhaustive list

**Comment by sundowndev** [comment]
Not sure I understand this one correctly, doesn't enumerator contain needed attributes already ? https://github.com/cloudskiff/driftctl/blob/main/pkg/remote/aws/vpc_security_group_rule_enumerator.go#L42

**Comment by eliecharra** [comment]
I didn't checked if middlewares already got their attributes, you can check if the middleware is working correctly without the detail fetcher and if it's ok then we can close this issue.
