### ISSUE TITLE
Output to ease terraform import of unmanaged resources in stdout mode

### ISSUE THREAD

**Issue by juno-yu** [cloudskiff/driftctl#856]
**Description**
- save manual efforts for concatting those "import id" https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule#import after discovering them 

- e.g. concatting those `Security Group Rules can be imported using the security_group_id, type, protocol, from_port, to_port, and source(s)/destination(s) (e.g. cidr_block) separated by underscores (_). All parts are required.` for tracking `aws_security_group_rule` is very time consuming 
 
**Example**
https://github.com/cloudskiff/driftctl/pull/855/files#diff-a7ff0d3ae4aee6ef9557be809cb7b567203efb928f66ef45fee67edbf8dedf3cR78

There might be many possible TODO extending this , like 
- hiding those unsupported by terraform 
- moving to logger
- adding flag to disable output
etc

**Comment by eliecharra** [comment]
Hi @juno-yu, sorry for the delay to get an answer 🙏🏻 

This will probably never be implemented, we want to keep driftctl focused on its main purpose and thus we want to avoid to have too many output formats.

Actually, you can achieve what you want by using the built in json output format combined with `jq` like this for example :

```
jq -r '.unmanaged[] | ["terraform import", ([.type, (["<PLACEHOLDER>", .id] | join(" "))] | join("."))] | join(" ")' test.json
terraform import aws_eip.<PLACEHOLDER> eipalloc-0d8abae9f0ccc816b
terraform import aws_internet_gateway.<PLACEHOLDER> igw-0149bd6d7a80b8a45
terraform import aws_security_group.<PLACEHOLDER> sg-040fc04ba76c6d7fc
terraform import aws_security_group.<PLACEHOLDER> sg-0a1ba2ffa4d002c9b
terraform import aws_security_group_rule.<PLACEHOLDER> sgrule-1867705370
terraform import aws_security_group_rule.<PLACEHOLDER> sgrule-2143039386
terraform import aws_security_group_rule.<PLACEHOLDER> sgrule-2412783029
terraform import aws_security_group_rule.<PLACEHOLDER> sgrule-3698744530
```

JSON format goal is to interoperate with more complex workflows, this is totally fine
