### ISSUE TITLE
tfstate should be checked for existence early in the process

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#86]
**Description**

Reported by @Gary-Armstrong on a #73 comment: 

```
After 17 minutes it completed reading AWS, and then it says

Unable to scan resources: Failed to read state file: The state file could not be read: read terraform.tfstate: is a directory
which is news to me :)
Maybe do this check at the start? 
```

Great suggestion, we should indeed check everything is at the right place early, especially when scanning huge AWS accounts takes a long time

**Environment**
 - OS: docker img
 - driftctl version: 0.2.3

**How to reproduce**

**Possible Solution**

Early check for existence of the `--from` value (or `DCTL_FROM` env var) 

**Additional context**

**Comment by eliecharra** [comment]
As IaC scan will often be very quick compared to cloud resource enumeration, this is definitely something we should do. The idea crossed my mind days ago when trying to debug an issue in my test suite, thanks to @Gary-Armstrong for putting this in spotlights 👍🏻

**Comment by eliecharra** [comment]
Should be fixed in v0.3.0, it was only broken for S3 remote state, be careful to try both local and remote state cases.

**Comment by sjourdan** [comment]
I confirm I immediately got the error  `open terraform.tfstate: no such file or directory` when running driftctl.

**Comment by eliecharra** [comment]
> I confirm I immediately got the error `open terraform.tfstate: no such file or directory` when running driftctl.

It was already working for local states, this issues concern only remote states

**Comment by sjourdan** [comment]
you're right! LGTM still :)
I found a limitation in our implementation, let me open a new issue.
