### ISSUE TITLE
Add resource source when scanning IaC

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#873]
**Description**
Be able to identify resources origin for resources coming from IaC. The final goal is to display resource source in the output.

**Solution**
We should create a new composed struct `StateResource` : 

```go
type ResourceSource struct {
	Module string
	Name   string
	State  string
}

type StateResource struct {
	AbstractResource
	Source ResourceSource
}
```

and when we read IaC code we should add `Source` to be able to track down the resource during the execution.

**Comment by sundowndev** [comment]
Following #877, may be we can add the state version as well, so in JSON and HTML output we'd have a list of iac sources. WDYT @cloudskiff/engineering  ? 

```diff
type ResourceSource struct {
	Module string
	Name   string
	State  string
+	Version  string
```

**Comment by eliecharra** [comment]
> Following #877, may be we can add the state version as well, so in JSON and HTML output we'd have a list of iac sources and their version. WDYT @cloudskiff/engineering ?
> 
> ```diff
> type ResourceSource struct {
> 	Module string
> 	Name   string
> 	State  string
> +	Version  string
> ```


Where does the #887 came from ? We didn't talked about it in technical meetings, and the issue descriptiojn is empty.
I can't say anything about it since I don't know what we want, maybe we should put it in `Under Investigation` ?
