### ISSUE TITLE
Display resource source in HTML output

### ISSUE THREAD

**Issue by sundowndev** [cloudskiff/driftctl#876]
**Description**

We want to display resource source in HTML output so we always know which IaC source the drift come from.

**Implementation details**

We can create a select input in which we'd have states. Exactly how the resource type select works. We must create a distinct list of IaC sources in order to use it in the HTML template. The select should filter on states.

We also want to remove the `Resource Type`

![image](https://user-images.githubusercontent.com/6154987/126764618-e252d7fe-d298-4c95-8ef7-3b4b965296c2.png)

In the old resource type column, change the format to : `MODULE.TYPE.NAME` like in console output.

**Example**

![image](https://user-images.githubusercontent.com/16480203/126764067-425f584d-ec17-4f29-a302-6416c8ebb90b.png)

Blocked by #873

**Comment by sjourdan** [comment]
LGTM

for a missing resource: 

![image](https://user-images.githubusercontent.com/419121/131985250-e00e1921-0eb4-46eb-ad1d-eb2ebdb23cb0.png)

for a changed resource: 

![image](https://user-images.githubusercontent.com/419121/131985312-0436fcc7-96a9-4bbb-8601-835a7da63e63.png)
