### ISSUE TITLE
Investigate AutoScalingGroup Support

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#899]
Like EKS, we should play with autoscaling groups with terraform and determine how can link other resources to a group (instances, ...)

**Comment by Valiev** [comment]
Any estimations on this?

**Comment by GeraldCrescione** [comment]
Hi @Valiev , just letting you know that part of the team is currently on vacation. They'll be back with some answers to your questions very soon. Apologies for the delayed response :)

**Comment by eliecharra** [comment]
Hi @Valiev the current investigation showed us that it may add some noise for EKS users if we add the autoscaling group without any solution to handle ones generated by an EKS cluster. For now we want to avoid too much noise and this this subject is blocked by a largest work on EKS, which is still in progress. This current issue was just created to measure the impacts, but the "real" issue to add support for autoscaling group is #925. I'm closing this one but you can subscribe on #925 notifications to stay informed.

**Comment by Valiev** [comment]
Great, thanks for letting me know! cc @eliecharra
