### ISSUE TITLE
Add support for `azurerm_storage_container`

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#903]
**Description**
Add support for `azurerm_storage_container` in **non-deep** mode.

**Prerequisites :**
- [x] QA Azure account for ACC tests @eliecharra 

**Solution :**
- Add new provider Azure.
- Add Enumerator for `azurerm_storage_container`, with an acceptance test.

**Comment by sjourdan** [comment]
initial tests are positive! I will try again and harder next week. This is great news.

**Comment by sjourdan** [comment]
LGTM at this point
