### ISSUE TITLE
JSON formatting is broken in HTML output

### ISSUE THREAD

**Issue by sundowndev** [cloudskiff/driftctl#921]
When we have a diff on a JSON field, the result in the HTML report is ugly. The reason is we use the same formatting function than console output. We should create a custom formatting function.

### To reproduce

- Apply terraform file below
```hcl
provider "aws" {
    region = "us-east-1"
}

terraform {
    required_providers {
        aws = {
            version = "3.47.0"
        }
    }
}

resource "random_string" "prefix" {
    length  = 6
    upper   = false
    special = false
}

resource "aws_s3_bucket" "foobar" {
    bucket = "${random_string.prefix.result}.foobar.driftctl-test.com"
}

resource "aws_s3_bucket_policy" "foobar" {
    bucket = aws_s3_bucket.foobar.bucket
    policy = <<POLICY
{
  "Version":"2012-10-17",
  "Statement":[
    {
      "Sid":"PublicRead",
      "Effect":"Allow",
      "Principal": "*",
      "Action":["s3:GetObject","s3:GetObjectVersion"],
      "Resource":"arn:aws:s3:::${random_string.prefix.result}.foobar.driftctl-test.com/*"
    }
  ]
}
POLICY
}

```
- Go to AWS console and edit the bucket policy
```diff
- "Effect":"Allow",
+ "Effect":"Deny",
```
- run driftctl in deep mode with html report
- check changed resources in HTML report, you'll see ASCII colors switched in the json diff
- **We expect here a valid json diff with colors**
### Screenshots

![image](https://user-images.githubusercontent.com/6154987/128708623-f40ed60c-8140-4c7c-84e2-bd968ecfff17.png)

**Comment by eliecharra** [comment]
Not that this should be covered by a test, and BTW this test change in test file can be removed :

```go
						{
							Change: diff.Change{
								Type: diff.UPDATE,
								Path: []string{"Policies", "0"},
								From: resource.Resource{},
								To:   resource.Resource{Id: "093cd6ba-cf6d-4800-b252-6a50ca8903cd", Type: "aws_iam_policy"},
							},
						},
```

**Comment by sjourdan** [comment]
LGTM 

crystal clear now 

![image](https://user-images.githubusercontent.com/419121/131985447-e0c27ce4-6c8b-4e3a-8a05-14736e8b5c57.png)
