### ISSUE TITLE
Add doc about `--filter` working only in deep mode

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#922]
**Description**
`--filter` on resource attributes work only in deep mode, we should update the documentation according to this.

**Comment by sundowndev** [comment]
May be we could display a warning or error message about that in the CLI ? Something like `--filter flag cannot be used without --deep flag`

**Comment by sjourdan** [comment]
@sundowndev it's best to clarify it right in the documentation as one can filter on just the resources id/type and not on attributes
