### ISSUE TITLE
Feature: Add ability to read provider version from .terraform.lock.hcl lock file

### ISSUE THREAD

**Issue by nantiferov** [cloudskiff/driftctl#929]
**Description**

Hello. Thank you for this wonderful tool 👍 

I think that it would be nice to have ability to read provider version from .terraform.lock.hcl lock file (if it exists). This way drift will be checked with the same version as used by terraform.

**Example**

By default it seems `3.19.0` is used in `driftctl scan` and it's possible to override it with `--tf-provider-version`.
While .terraform.lock.hcl lock file always has provider version in it, so it could be easily read from there.

**Comment by sjourdan** [comment]
Great idea, we are prioritizing it. More specs and use-cases are coming

**Comment by eliecharra** [comment]
**Note for maintainers:**

We can use https://github.com/hashicorp/hcl#hcl to read the `.terraform.lock.hcl` file if it exist and use the decoded version from it.

We should change the `ProviderInstaller` constructor `NewProviderInstaller` to remove the version, and instead pass the version to the `Install()` func : `func (p *ProviderInstaller) Install(version string) (string, error)`.

And so we can handle the new logic to retrieve the version from the lock file in `func (p *TerraformProvider) configure(alias string)` at the begining of the func.

We should also change each `resourceSchemaRepository.Init`  call to use `provider.Version()`

The default version statement should be moved within provider constructor method, for AWS it should be in `NewAWSTerraformProvider`

**Comment by sjourdan** [comment]
I couldn't replicate the required behavior. 

w/0.15 as expected, 3.19 default version was loaded: 

```sh
❯  head .terraform.lock.hcl 
provider "registry.terraform.io/hashicorp/aws" {
  version     = "3.44.0"
  constraints = ">= 3.36.0, 3.44.0"
[...]
❯  LOG_LEVEL=debug driftctl scan 
[...]
DEBU[0000] Found existing provider path=/home/sjourdan/.driftctl/plugins/linux_amd64/terraform-provider-aws_v3.19.0_x5
```

w/0.16 unexpectedly loaded 3.19 too: 

```sh
❯  head .terraform.lock.hcl 
provider "registry.terraform.io/hashicorp/aws" {
  version     = "3.44.0"
  constraints = ">= 3.36.0, 3.44.0"
[...]
❯  driftctl-0.16-pre scan
DEBU[0000] Found existing provider path=/home/sjourdan/.driftctl/plugins/linux_amd64/terraform-provider-aws_v3.19.0_x5
```

**Comment by sjourdan** [comment]
:arrow_up: previous comment was my mistake, forgot to rebuild #pebcak 

LGTM! :grin: 

```sh
❯  driftctl-0.16-pre scan 
[...]DEBU[0000] Error while parsing terraform lock file error=no diagnostics
DEBU[0000] Found provider version in terraform lock file provider=aws+tf version=3.44.0
DEBU[0000] Found existing provider path=/home/sjourdan/.driftctl/plugins/linux_amd64/terraform-provider-aws_v3.44.0_x5
[...]
```

Works well also with a non-available provider: 

```sh
❯  driftctl-0.16-pre scan 
[...]DEBU[0000] Error while parsing terraform lock file error=no diagnostics
DEBU[0000] Found provider version in terraform lock file provider=aws+tf version=3.44.0
DEBU[0000] New provider library created
DEBU[0000] provider not found, downloading ... path=/home/sjourdan/.driftctl/plugins/linux_amd64/terraform-provider-aws_v3.44.0
DEBU[0000] Downloading provider path=/home/sjourdan/.driftctl/plugins/linux_amd64 url=https://releases.hashicorp.com/terraform-provider-aws/3.44.0/terraform-provider-aws_3.44.0_linux_amd64.zip
DEBU[0005] Decompressing archive dst=/home/sjourdan/.driftctl/plugins/linux_amd64 src=/tmp/terraform-provider830568806
DEBU[0007] Download successful
```

To be sure, default 3.19 provider version was deleted from this test environment: 

```sh 
❯  file /home/sjourdan/.driftctl/plugins/linux_amd64/terraform-provider-aws_v3.19*
/home/sjourdan/.driftctl/plugins/linux_amd64/terraform-provider-aws_v3.19*: cannot open `/home/sjourdan/.driftctl/plugins/linux_amd64/terraform-provider-aws_v3.19*' (No such file or directory)
```

thanks @eliecharra @sundowndev ;-)
