### ISSUE TITLE
Output HTML does not show drifts when coverage is 100%

### ISSUE THREAD

**Issue by sundowndev** [cloudskiff/driftctl#935]
**Description**
Coverage doesn't decrease when we only have some drifts on managed resources. Actually in HTML output, we check coverage is less than 100 to know if infrastructure is in sync or not. We should not do that because as soon as a user has only drifts on managed resources, the HTML output will falsely show that the infrastructure is in sync.

Originally discovered by @eliecharra 

**Environment**
 - OS: linux
 - driftctl version: main
 - terraform version: 1.0.2
 - terraform providers versions: aws@3.47.0

**How to reproduce**

1. Create s3 bucket with policy
2. Run tf apply
3. Edit from the console
4. Ignore any unmanaged/missing resources
5. Run the scan with deep mode and HTML output

```hcl
resource "random_string" "prefix" {
  length  = 6
  upper   = false
  special = false
}

resource "aws_s3_bucket" "foobar" {
  bucket = "${random_string.prefix.result}.foobar.driftctl-test.com"
}

resource "aws_s3_bucket_policy" "foobar" {
  bucket = aws_s3_bucket.foobar.bucket
  policy = <<POLICY
{
  "Version":"2012-10-17",
  "Statement":[
    {
      "Sid":"PublicRead",
      "Effect":"Allow",
      "Principal": "*",
      "Action":["s3:GetObject","s3:GetObjectVersion"],
      "Resource":"arn:aws:s3:::${random_string.prefix.result}.foobar.driftctl-test.com/*"
    }
  ]
}
POLICY
}
```

**Possible Solution**
Instead of checking coverage value, we could add a parameter such as `IsInSync` which will be used by the template to know whenever we should display drifts.

**Comment by sjourdan** [comment]
LGTM 

definitely not 100% anymore 

![image](https://user-images.githubusercontent.com/419121/131985670-7c0577c5-87de-4981-834f-6bafd264d573.png)

**Comment by sjourdan** [comment]
got it right this time and still LGTM :) 

- 100% coverage 
- a manual drift on a resource on one of the states
- diff is now displayed 
- tested on GCP as well

![image](https://user-images.githubusercontent.com/419121/132368225-c63241b1-7009-46fd-8247-ab241ab1bdb7.png)
