### ISSUE TITLE
Support aws_rds_cluster_instance

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#954]
**Description**

`aws_rds_cluster_instance` provides an RDS Cluster Instance Resource

**Example**

Doc: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance

**Comment by sundowndev** [comment]
Following https://github.com/cloudskiff/driftctl/issues/947#issuecomment-911777671, we should create a middleware to handle false positives on `aws_db_instance` resources according to `aws_rds_cluster_instance` resources present in the state. For each `aws_rds_cluster_instance` in the state, ignore any remote `aws_db_instance` that matches the same resource id.

**Comment by sjourdan** [comment]
LGTM 

< 0.16

```sh
❯  LOG_LEVEL=error driftctl scan --tf-provider-version 3.61.0
Found resources not covered by IaC:
  aws_db_instance:
    - aurora-cluster-demo-0
    - aurora-cluster-demo-1
    - aurora-cluster-demo-2
[...]
Found 9 resource(s)
 - 0% coverage
 - 0 resource(s) managed by terraform
     - 0/0 resource(s) out of sync with Terraform state
 - 9 resource(s) not managed by Terraform
 - 0 resource(s) found in a Terraform state but missing on the cloud provider
[...]
```

w/0.16: 

```sh
❯  LOG_LEVEL=error driftctl-0.16-pre scan --tf-provider-version 3.61.0
Found resources not covered by IaC:
[...]
Found 13 resource(s)
 - 30% coverage
 - 4 resource(s) managed by terraform
     - 0/4 resource(s) out of sync with Terraform state
 - 9 resource(s) not managed by Terraform
 - 0 resource(s) found in a Terraform state but missing on the cloud provider

```
